import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the coverage reporter, and rewritten on every run.
    "coverage/**",
    // Throwaway probes. They are not shipped and they are not reviewed; a
    // linter complaining about one is noise in a gate that has to stay
    // worth reading. `.scratch` is already gitignored.
    ".scratch/**",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
