import type { MetadataRoute } from "next";

/**
 * What makes this installable on her phone.
 *
 * `display: standalone` is the part that matters: launched from the home
 * screen it opens without browser chrome, which is the whole difference
 * between a bookmark and something that feels like an app. Chrome will only
 * offer to install with a 192 and a 512 icon present, which is why both exist.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "Coach",
    short_name: "Coach",
    description: "Your strength and nutrition coach",
    // Straight into today's session — "/" only redirects here.
    start_url: "/train",
    scope: "/",
    display: "standalone",
    background_color: "#0b0e13",
    theme_color: "#0b0e13",
    orientation: "portrait",
    categories: ["health", "fitness"],
    // Generated by route handlers — no binaries in the repo to keep in sync
    // with the app's own colours.
    icons: [
      { src: "/icon", sizes: "64x64", type: "image/png" },
      { src: "/icon-192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable: Android crops icons to whatever shape the launcher uses, and
      // without this it crops the mark itself rather than the padding.
      { src: "/icon-512", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
