import Link from "next/link";
import { LEGAL } from "@/lib/legal";

export const metadata = { title: "Terms" };

/**
 * Terms of use, and the one paragraph that matters most: this is a coach, not
 * a clinician, and it says so in the same plain register as the rest of the
 * app rather than in a block of capitals nobody reads.
 */
export default function TermsPage() {
  return (
    <article className="mx-auto max-w-2xl px-6 py-10 text-[15px] leading-relaxed">
      <p className="text-[11px] font-semibold uppercase tracking-widest text-accent">{LEGAL.appName}</p>
      <h1 className="mt-1 text-3xl font-bold tracking-tight">Terms of use</h1>
      <p className="mt-1 text-[13px] text-muted">Effective {LEGAL.effectiveDate}. Operated by {LEGAL.operator}, {LEGAL.jurisdiction}.</p>

      <H2>What this is</H2>
      <P>
        {LEGAL.appName} is a personal strength and nutrition coach. It writes training weeks,
        plans meals, tracks what you log, and talks with you about it. By using it you agree to
        these terms and to the <Link href="/privacy" className="underline underline-offset-2">privacy policy</Link>.
      </P>

      <H2>It is a coach, not a doctor</H2>
      <P>
        Nothing in {LEGAL.appName} is medical advice, and the coach is not a clinician. It is
        general guidance built from published exercise and nutrition evidence, applied to what you
        have told it. It cannot examine you and it does not know what it has not been told.
      </P>
      <P>
        This matters most where the app is most careful: coming back from childbirth, pain, and
        anything involving your cycle. The app will tell you to see a professional in those cases,
        and it means it. Before starting or changing an exercise or nutrition programme, and
        especially if you are pregnant, recently gave birth, have a medical condition, or have been
        told to limit activity, talk to a doctor, midwife or physiotherapist. Pain that is sharp,
        joint-centred or lingering means stop.
      </P>

      <H2>Your account</H2>
      <P>
        Accounts are by invitation. You are responsible for keeping your sign-in to yourself. You
        can delete your account at any time from Settings, and everything the app holds about
        you goes with it, immediately and permanently.
      </P>

      <H2>Your data</H2>
      <P>
        It is yours. The privacy policy says what the app holds, where it goes and why. The app
        never sells it and never uses it for advertising.
      </P>

      <H2>The coach</H2>
      <P>
        The coach is generated by a language model. It will sometimes be wrong. It estimates
        calories and portions, and an estimate is not a measurement; when it looks something up
        against the food library it says so, and when it guesses it says that too. Numbers about
        your body are trends, not verdicts, and the app is built not to read one morning on the
        scale as progress or failure.
      </P>
      <P>
        Each account has a daily allowance for the coach so that a runaway conversation cannot
        spend money nobody is watching. When it is used up, everything else keeps working and the
        coach is back the next day.
      </P>

      <H2>Friends</H2>
      <P>
        Sharing training with someone requires both of you to agree, shows training only, and can
        be ended by either of you. Do not share a code with someone you do not want seeing your
        sessions.
      </P>

      <H2>Age</H2>
      <P>{LEGAL.appName} is for adults aged {LEGAL.minimumAge} and over.</P>

      <H2>Availability and liability</H2>
      <P>
        The app is provided as is. It may be unavailable, and it may change. To the extent the
        law allows, the operator is not liable for loss or injury arising from use of the app,
        including from acting on the coach&apos;s guidance without professional advice. Nothing in
        these terms limits rights that cannot be limited under the law of {LEGAL.jurisdiction}.
      </P>

      <H2>Contact</H2>
      <P>{LEGAL.contact}</P>

      <p className="mt-10 text-[13px] text-faint">
        <Link href="/privacy" className="underline underline-offset-2">Privacy</Link>
        {" · "}
        <Link href="/login" className="underline underline-offset-2">Sign in</Link>
      </p>
    </article>
  );
}

const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 className="mt-8 text-[17px] font-semibold">{children}</h2>
);
const P = ({ children }: { children: React.ReactNode }) => (
  <p className="mt-2 text-muted">{children}</p>
);
