/**
 * What to show her while a tool runs — "logging your set", not `log_set`.
 *
 * One map, imported by every surface that streams the coach: the chat, the
 * inline threads, and the server loop. It lived in two places before, and the
 * server's copy had quietly fallen twenty tools behind the browser's.
 *
 * tests/tool-coverage.test.ts fails the build if a registered tool is missing
 * from here, because the fallback is a spinner that says nothing.
 */
export const TOOL_LABELS: Record<string, string> = {
  list_shipped_for_me: "checking what shipped for you", acknowledge_shipped: "noting that down",
  get_calories_burned: "working out what your training cost",
  set_postpartum_status: "noting where you are in recovery",
  get_postpartum_plan: "checking what is right for your recovery",
  list_themes: "looking at the themes", set_theme: "changing how the app looks",
  get_share_code: "finding your friend code", reset_share_code: "issuing a new friend code",
  add_friend: "sending that friend request", list_friends: "checking your friends",
  respond_to_friend_request: "answering that request", remove_friend: "removing that friend",
  get_friend_stats: "checking how your friends are training",
  get_profile: "reading your profile", update_profile: "saving your details",
  log_cycle_event: "noting that down", get_cycle_status: "checking where you are in your cycle",
  log_weight: "logging your weigh-in", get_weight_history: "checking your weight trend",
  remove_weigh_in: "removing that weigh-in", delete_workout: "removing that session",
  remove_measurement: "removing that measurement",
  update_goal: "updating your milestone", remove_goal: "removing that milestone",
  add_shopping_extra: "adding that to your list", remove_shopping_extra: "taking that off your list",
  clear_plan: "clearing your week", copy_week: "copying that week across",
  add_planned_meal: "adding that meal", remove_planned_meal: "taking that meal off",
  delete_progress_photos: "deleting your photos", clear_range: "clearing those days",
  forget_conversation: "forgetting that",
  set_goal: "setting a milestone", list_goals: "reviewing your goals",
  achieve_goal: "marking a milestone hit", search_exercises: "searching exercises",
  get_exercise_guide: "pulling up the form guide", create_weekly_plan: "building your week",
  get_plan: "checking your plan", adjust_plan_day: "adjusting your plan",
  start_workout: "starting your session", log_set: "logging your set",
  delete_set: "taking that set off", correct_set: "correcting that set",
  finish_workout: "wrapping up", get_exercise_history: "looking up your history",
  get_week_review: "reviewing your week", create_meal_plan: "planning your meals",
  start_maintenance_phase: "setting up your break", end_maintenance_phase: "getting back to it",
  set_equipment_override: "noting what you've got with you",
  clear_equipment_override: "putting your usual kit back",
  run_check_in: "working out what you actually burn",
  set_nutrition_targets: "updating your targets",
  get_meal_plan: "checking your meals", swap_meal: "swapping that meal",
  get_meal_recipe: "writing out the recipe",
  log_cook_session: "noting what you cooked", list_prepped_portions: "checking the fridge",
  eat_prepped_portion: "logging that portion", adjust_prepped_portion: "updating the count",
  log_meal: "logging your meal", update_meal_log: "correcting that entry",
  clear_meal_logs: "clearing that day's food", get_day_nutrition: "totalling today's food",
  get_fact: "finding something worth knowing",
  lookup_food: "looking up the macros", find_recipes: "finding recipes",
  search_food_library: "searching the food library",
  search_ingredient: "looking that ingredient up",
  get_nutrition_trend: "reviewing how you've been eating",
  get_recent_meals: "finding your usuals", remove_meal_log: "removing that entry",
  suggest_meals: "looking for something different", suggest_exercises: "finding you options",
  get_shopping_list: "building your shopping list",
  get_pantry: "checking your kitchen", add_to_pantry: "putting the shopping away",
  set_pantry_item: "updating your kitchen", clear_pantry: "clearing your kitchen", remove_pantry_item: "clearing that off the shelf",
  mark_shopping_bought: "putting the shopping away",
  run_plan_setup: "setting up your plan", skip_plan_setup: "putting that away",
  send_shopping_list_to_instacart: "sending your list to Instacart",
  log_measurement: "saving your measurement", get_measurements: "checking your measurements",
  get_measuring_guide: "pulling up the measuring guide",
  estimate_body_composition: "working that out from your measurements",
  get_strength_standard: "seeing where that lift sits",
  get_exercise_progression: "tracking your progression",
  check_progression_status: "seeing what's still moving", schedule_deload: "planning a lighter week",
  get_next_targets: "working out your weights", get_weekly_volume: "adding up your week", estimate_one_rep_max: "estimating your max",
  suggest_substitutes: "finding you an alternative",
  substitute_exercise: "swapping that movement",
  log_complaint: "noting where it hurts", resolve_complaint: "marking that settled",
  list_complaints: "checking what's bothering you",
  add_exercise_to_day: "adding that to your day",
  remove_exercise_from_day: "taking that off your day",
  list_templates: "looking through the templates", suggest_template: "finding you a template",
  apply_template: "setting up your plan",
  add_progress_photo: "saving your photo", list_progress_photos: "finding your photos",
  delete_progress_photo: "deleting that photo",
  get_boost: "finding you a boost", get_coach_usage: "checking your coach usage",
  set_coach_budget: "updating your allowance",
  change_exercise: "renaming that movement",
  remove_logged_exercise: "taking that movement off the day",
  erase_all_my_data: "erasing everything",
  set_rest_defaults: "setting your rest times",
  save_meal: "saving that meal",
  list_saved_meals: "checking your regulars",
  remove_saved_meal: "removing that saved meal",
  set_weigh_in_reminder: "setting your weigh-in reminder",
  record_weigh_in_reminder: "noting that reminder",
  save_push_device: "turning on notifications",
  forget_push_device: "turning off notifications",
  export_transcript: "writing out your conversation",
  submit_feedback: "passing that on", list_feedback: "reading your feedback",
};

export const toolLabel = (name: string) => TOOL_LABELS[name] ?? name.replace(/_/g, " ");
