import { groupForMuscle } from "./muscle-groups";

/**
 * Hard sets per muscle group per week.
 *
 * Written for the planner more than for her. The week is generated by a model
 * with no numeric check on balance, so it can and does produce a week where
 * quads get four sets and shoulders get twenty-two — and nothing anywhere
 * notices. This is the check.
 *
 * What it is *not* is a target to chase. Volume landmarks are population
 * ranges with enormous individual spread, and turning them into a score she
 * tries to max out is how a sensible programme becomes junk volume and a sore
 * back. She sees balance — "shoulders got less than the plan asked for" —
 * never a number to beat.
 */

/**
 * The library names ~49 muscles; a person thinks in about nine. Anything not
 * mapped is deliberately dropped rather than bucketed as "other": a set of
 * grip work is not a set of anything a landmark applies to.
 */
/**
 * One mapping for the whole app — see lib/muscle-groups.ts. Volume folds
 * Glutes into Legs, because the landmarks below are written for the leg as a
 * training unit rather than for how someone searches a library.
 */
/**
 * Work that is real but that no volume landmark describes. Grip, neck and
 * conditioning belong in the library — she goes looking for them — and
 * counting them as sets of "Arms" would inflate a number these landmarks are
 * not about. They are reported as unmapped instead of hidden.
 */
const NOT_VOLUME = new Set([
  "grip", "wrist", "elbow", "neck", "deep neck flexors", "cardiovascular",
  "diaphragm", "pelvic floor", "ankles", "knee", "foot", "achilles",
  "plantar fascia", "thoracic spine", "posterior shoulder capsule",
]);

export const muscleGroup = (muscle: string): string | null => {
  if (NOT_VOLUME.has(muscle.trim().toLowerCase())) return null;
  const group = groupForMuscle(muscle);
  // Glutes are their own group in the library, because that is how she looks
  // for an exercise; here they are part of the leg as a training unit.
  return group === "Glutes" ? "Legs" : group;
};

/**
 * Weekly landmarks, in hard sets, for someone in her first year training.
 *
 * Deliberately below the numbers you see quoted for intermediates: she is
 * training in a calorie deficit, where recovery is the binding constraint, and
 * the cost of too much is an injury that stops everything.
 */
export const LANDMARKS: Record<string, { enough: number; plenty: number }> = {
  Legs: { enough: 8, plenty: 18 },
  Back: { enough: 8, plenty: 18 },
  Chest: { enough: 4, plenty: 12 },
  Shoulders: { enough: 4, plenty: 12 },
  Arms: { enough: 2, plenty: 10 },
  Core: { enough: 3, plenty: 12 },
};

export type GroupVolume = {
  group: string;
  sets: number;
  /** below — under what a week needs; ok; above — more than she can recover from. */
  status: "below" | "ok" | "above";
  enough: number;
  plenty: number;
};

export function weeklyVolume(
  sets: { muscles: string[] }[],
): { groups: GroupVolume[]; unmapped: number } {
  const counts = new Map<string, number>();
  let unmapped = 0;

  for (const set of sets) {
    // One set counts once per muscle group it works, not once per muscle: a
    // row that lists lats, upper back and rhomboids is one set of Back.
    const groups = new Set(
      set.muscles.map(muscleGroup).filter((g): g is string => g !== null),
    );
    if (groups.size === 0) { unmapped++; continue; }
    for (const g of groups) counts.set(g, (counts.get(g) ?? 0) + 1);
  }

  const groups = Object.keys(LANDMARKS).map((group) => {
    const sets = counts.get(group) ?? 0;
    const { enough, plenty } = LANDMARKS[group];
    return {
      group, sets, enough, plenty,
      status: sets < enough ? "below" as const : sets > plenty ? "above" as const : "ok" as const,
    };
  });

  return { groups, unmapped };
}

/** One line for the planner: what last week actually contained. */
export function volumeBrief(volume: { groups: GroupVolume[] }): string {
  const parts = volume.groups.map((g) => `${g.group} ${g.sets}`);
  const thin = volume.groups.filter((g) => g.status === "below").map((g) => g.group);
  const heavy = volume.groups.filter((g) => g.status === "above").map((g) => g.group);
  return [
    `Hard sets last week by group: ${parts.join(", ")}.`,
    thin.length ? `Light on: ${thin.join(", ")}.` : "",
    heavy.length ? `Already plenty of: ${heavy.join(", ")} — do not add more.` : "",
  ].filter(Boolean).join(" ");
}
