type FactSeed = {
  slug: string;
  category: "sedentary_risk" | "strength" | "nutrition" | "recovery" | "motivation" | "womens_health";
  text: string;
  source?: string;
};

/**
 * Facts the coach can drop in when they connect to what she just did. Written
 * to be true and useful rather than alarming — each one should change a
 * decision, not just impress.
 */
export const FACTS: FactSeed[] = [
  // ── The cost of sitting ───────────────────────────────────────────────────
  { slug: "sitting-mortality", category: "sedentary_risk",
    text: "Long uninterrupted sitting is linked to higher all-cause mortality, and it's a separate risk from not exercising. A pooled analysis of over a million people found that roughly 60–75 minutes of daily moderate activity largely offsets the risk of even 8 hours of sitting.",
    source: "Ekelund et al., The Lancet, 2016" },
  { slug: "sitting-glucose", category: "sedentary_risk",
    text: "Breaking up sitting with just 2 minutes of light walking every 20–30 minutes measurably lowers the blood sugar and insulin spikes that follow a meal. The interruption matters more than the intensity.",
    source: "Dunstan et al., Diabetes Care, 2012" },
  { slug: "standing-desk-myth", category: "sedentary_risk",
    text: "A standing desk on its own does surprisingly little. What the research keeps pointing at is movement — changing position and walking a few minutes an hour — not the posture you hold still in.",
    source: "Cochrane review, 2018" },
  { slug: "sitting-hip-flexors", category: "sedentary_risk",
    text: "Hours of sitting keeps the hip flexors in a shortened position, which quietly tilts the pelvis and makes the glutes lazier at doing their job. It's a major reason desk workers feel tight in the lower back and weak in the hips.",
    source: "Journal of Physical Therapy Science" },
  { slug: "sedentary-back-pain", category: "sedentary_risk",
    text: "For chronic low back pain, exercise beats rest in essentially every high-quality trial. Movement is the treatment, not the risk.",
    source: "JAMA Internal Medicine, 2016" },
  { slug: "vo2max-mortality", category: "sedentary_risk",
    text: "In a study of over 122,000 people, cardiorespiratory fitness predicted survival more strongly than smoking, diabetes, or high blood pressure. Being unfit carried a greater risk than any of the traditional risk factors measured.",
    source: "Mandsager et al., JAMA Network Open, 2018" },
  { slug: "steps-mortality", category: "sedentary_risk",
    text: "Mortality risk drops steeply as daily steps rise from about 3,000 to 7,000, then flattens out. You don't need 10,000 — you need to not be at 3,000.",
    source: "Paluch et al., JAMA Network Open, 2021" },
  { slug: "sitting-circulation", category: "sedentary_risk",
    text: "An hour of uninterrupted sitting measurably reduces blood flow in the leg arteries — and a 5-minute walk restores it completely. The damage isn't cumulative if you interrupt it.",
    source: "Thosar et al., Medicine & Science in Sports & Exercise, 2015" },
  { slug: "exercise-cognition", category: "sedentary_risk",
    text: "Regular aerobic exercise is associated with larger hippocampal volume and better memory in adults. Sedentary time works the other direction.",
    source: "Erickson et al., PNAS, 2011" },

  // ── Strength ──────────────────────────────────────────────────────────────
  { slug: "muscle-decline-30", category: "strength",
    text: "From your thirties onward, adults lose roughly 3–8% of muscle mass per decade without resistance training — and the rate accelerates after 60. Lifting is the only intervention that reliably reverses it.",
    source: "Volpi et al., Clinical Nutrition, 2004" },
  { slug: "strength-mortality", category: "strength",
    text: "Strength training twice a week is associated with lower all-cause mortality, independent of how much cardio you do. Two sessions is the point where the curve bends.",
    source: "Momma et al., British Journal of Sports Medicine, 2022" },
  { slug: "grip-strength", category: "strength",
    text: "Grip strength predicts cardiovascular mortality better than systolic blood pressure does. It's a proxy for total body strength — which is a proxy for how well you're aging.",
    source: "Leong et al., The Lancet (PURE study), 2015" },
  { slug: "neural-gains", category: "strength",
    text: "Most of your strength gain in the first 4–6 weeks isn't new muscle — it's your nervous system learning to recruit what you already have. That's why beginners improve so fast, and why those early jumps are real even before anything looks different.",
    source: "Sale, Medicine & Science in Sports & Exercise" },
  { slug: "progressive-overload", category: "strength",
    text: "Muscle adapts to demand and then stops. Progressive overload — a rep more, a pound more, a better-controlled tempo — is the entire mechanism. Doing the same workout for months is maintenance, not progress.",
    source: "Principle of progressive overload" },
  { slug: "detraining", category: "strength",
    text: "Strength holds up for about three to four weeks without training. One missed session is statistically nothing — the fitness you built doesn't evaporate because of a bad week.",
    source: "Mujika & Padilla, Sports Medicine, 2000" },
  { slug: "muscle-memory", category: "strength",
    text: "Muscle cells keep the extra nuclei they gained from previous training, possibly permanently. Rebuilding lost muscle is genuinely faster than building it the first time — the work you've already done isn't wasted.",
    source: "Gundersen, Journal of Experimental Biology, 2016" },
  { slug: "muscle-calories-myth", category: "strength",
    text: "A pound of muscle burns about 6 calories a day at rest, not the 50 you'll see repeated online. Muscle is worth building for strength, glucose control, bone density, and shape — the metabolic bump is a bonus, not the reason.",
    source: "Wang et al., American Journal of Clinical Nutrition, 2010" },
  { slug: "rest-between-sets", category: "strength",
    text: "For strength on compound lifts, 2–3 minutes between sets produces better results than 1 minute. Cutting rest short to save time mostly just makes the next set worse.",
    source: "Schoenfeld et al., Journal of Strength & Conditioning Research, 2016" },
  { slug: "compound-first", category: "strength",
    text: "Do the exercise that matters most first, while you're fresh. Squats after twenty minutes of arm work are a worse squat session — order is a training variable.",
    source: "Exercise order research, ACSM" },
  { slug: "form-before-load", category: "strength",
    text: "Adding weight to a movement pattern you can't yet control just makes the flawed pattern stronger. Own the technique at a weight that feels easy, then climb.",
    source: "Coaching principle" },
  { slug: "unilateral-imbalance", category: "strength",
    text: "Single-leg and single-arm work exposes side-to-side imbalances that barbell lifts happily hide. That's a feature — imbalances you can see are imbalances you can fix.",
    source: "Journal of Strength & Conditioning Research" },
  { slug: "insulin-sensitivity", category: "strength",
    text: "A single resistance training session improves insulin sensitivity for up to 24 hours afterward. Muscle is where most of your blood glucose gets stored — more of it means better handling of every meal.",
    source: "Holten et al., Diabetes, 2004" },

  // ── Nutrition ─────────────────────────────────────────────────────────────
  { slug: "protein-threshold", category: "nutrition",
    text: "Benefits for building and keeping muscle plateau around 1.6 g of protein per kg of body weight per day. Beyond that, extra protein mostly just costs money.",
    source: "Morton et al., British Journal of Sports Medicine, 2018" },
  { slug: "protein-during-deficit", category: "nutrition",
    text: "Dieting without enough protein or resistance training means roughly a quarter of the weight you lose is muscle rather than fat. Protein plus lifting is what makes it fat you're losing.",
    source: "Cava et al., Advances in Nutrition, 2017" },
  { slug: "protein-satiety", category: "nutrition",
    text: "Protein is the most filling macronutrient per calorie, and it costs 20–30% of its own calories just to digest — versus about 5% for fat. High protein makes a deficit easier to actually hold.",
    source: "Halton & Hu, Journal of the American College of Nutrition, 2004" },
  { slug: "deficit-size", category: "nutrition",
    text: "Losing more than about 1% of body weight per week increasingly costs muscle and gets harder to sustain. Slower loss keeps more of the weight off afterward — this is one place where being impatient loses.",
    source: "Garthe et al., International Journal of Sport Nutrition, 2011" },
  { slug: "fiber-satiety", category: "nutrition",
    text: "Most adults eat around half the fiber they need. Fiber slows digestion, blunts blood sugar spikes, and keeps you full — it's the cheapest appetite management available.",
    source: "Dietary Guidelines for Americans" },
  { slug: "liquid-calories", category: "nutrition",
    text: "Calories you drink barely register as food to your appetite system — you don't eat less later to compensate. It's the single easiest place to find a few hundred calories.",
    source: "Mattes, Physiology & Behavior, 2006" },
  { slug: "water-weight", category: "nutrition",
    text: "Body weight swings 2–4 lb day to day from water, sodium, glycogen, and digestion. A single weigh-in is noise; the direction across two weeks is the signal.",
    source: "Body composition measurement research" },
  { slug: "glycogen-water", category: "nutrition",
    text: "Every gram of stored carbohydrate holds about 3 grams of water. That's why a low-carb day drops the scale fast and a pasta dinner puts it back — neither is fat.",
    source: "Kreitzman et al., American Journal of Clinical Nutrition, 1992" },
  { slug: "spot-reduction", category: "nutrition",
    text: "You can't choose where fat comes off. Crunches build the muscle underneath but don't burn the fat above it — where you lose from is genetics and hormones, and it evens out over time.",
    source: "Ramírez-Campillo et al., Journal of Strength & Conditioning Research, 2013" },
  { slug: "neat", category: "nutrition",
    text: "Non-exercise movement — fidgeting, pacing, taking the stairs — can differ by hundreds of calories a day between two similar people. Deficits often stall because this quietly drops, not because metabolism broke.",
    source: "Levine et al., Science, 1999" },
  { slug: "alcohol-recovery", category: "nutrition",
    text: "Alcohol after training suppresses muscle protein synthesis by roughly a third, even when protein is eaten alongside it. It's not forbidden — it's just worth knowing what it costs.",
    source: "Parr et al., PLOS ONE, 2014" },
  { slug: "meal-timing", category: "nutrition",
    text: "Total daily protein and calories matter far more than exact timing. The 'anabolic window' is more like several hours than thirty minutes — you don't have to sprint to a shaker.",
    source: "Schoenfeld et al., Journal of the International Society of Sports Nutrition, 2013" },
  { slug: "adherence-beats-diet", category: "nutrition",
    text: "Head-to-head trials of low-carb, low-fat, and everything between keep finding the same thing: the diet people stick to is the one that works. There's no metabolic trick that beats adherence.",
    source: "Gardner et al., JAMA, 2018" },

  { slug: "waist-vs-bmi", category: "nutrition",
    text: "Waist circumference predicts cardiovascular and diabetes risk better than BMI does, because it reflects visceral fat around the organs rather than total mass. A tape measure tells you something the scale genuinely cannot.",
    source: "Ross et al., Nature Reviews Endocrinology, 2020" },
  { slug: "waist-target-women", category: "womens_health",
    text: "For women, a waist under about 35 inches (88cm) is the usual threshold for meaningfully lower metabolic risk. It's a better weekly target than a scale number, and it moves for reasons you control.",
    source: "World Health Organization / NIH guidance" },
  { slug: "recomposition", category: "strength",
    text: "Beginners returning to lifting often build muscle and lose fat at the same time. The scale barely moves for weeks while clothes fit differently and the waist drops — that's body recomposition, not a stall, and it's one of the best things that can happen early on.",
    source: "Barakat et al., Strength & Conditioning Journal, 2020" },
  { slug: "measure-consistently", category: "motivation",
    text: "Measure at the same time of day, ideally first thing before eating, and the same day each week. Most week-to-week measurement noise is tape placement and hydration rather than any real change.",
    source: "Body composition measurement practice" },

  // ── Recovery ──────────────────────────────────────────────────────────────
  { slug: "sleep-fat-loss", category: "recovery",
    text: "Dieters sleeping 5.5 hours instead of 8.5 lost the same total weight — but 55% less of it was fat, and more of it was muscle. Sleep decides what kind of weight comes off.",
    source: "Nedeltcheva et al., Annals of Internal Medicine, 2010" },
  { slug: "sleep-hunger", category: "recovery",
    text: "One short night raises ghrelin and lowers leptin, which is a hormonal way of saying you'll be hungrier tomorrow and it isn't a willpower failure.",
    source: "Spiegel et al., Annals of Internal Medicine, 2004" },
  { slug: "doms-not-a-metric", category: "recovery",
    text: "Soreness peaks 24–72 hours after a session and tracks how unfamiliar the movement was, not how effective it was. Some of the best training weeks leave you barely sore.",
    source: "Cheung et al., Sports Medicine, 2003" },
  { slug: "rest-days-build", category: "recovery",
    text: "Training is the stimulus; the adaptation happens while you rest. Rest days aren't time off from progress — they're when the progress is actually made.",
    source: "Supercompensation principle" },
  { slug: "walking-recovery", category: "recovery",
    text: "Easy walking on rest days increases blood flow to sore muscles and tends to reduce soreness rather than add to it. Recovery is usually active, not motionless.",
    source: "Dupuy et al., Frontiers in Physiology, 2018" },
  { slug: "stress-recovery", category: "recovery",
    text: "High life stress measurably slows recovery from training — the same workout takes longer to bounce back from during a hard week. Scaling back during a rough patch is strategy, not weakness.",
    source: "Stults-Kolehmainen & Bartholomew, Medicine & Science in Sports & Exercise, 2012" },
  { slug: "exercise-sleep-quality", category: "recovery",
    text: "Regular exercise improves both how fast you fall asleep and how deeply you sleep — and better sleep makes the next session better. It compounds in both directions.",
    source: "Kredlow et al., Journal of Behavioral Medicine, 2015" },

  // ── Women's health ────────────────────────────────────────────────────────
  { slug: "women-bulking-myth", category: "womens_health",
    text: "Women produce roughly a fifteenth of the testosterone men do, which is why lifting heavy builds strength and shape rather than bulk. The look people actually want almost always requires more muscle, not less.",
    source: "Endocrine physiology" },
  { slug: "peak-bone-mass", category: "womens_health",
    text: "Peak bone mass is reached around age 30, and resistance training is one of the few things that meaningfully builds and preserves it afterward. Loading bone in your thirties is a deposit against your sixties.",
    source: "National Osteoporosis Foundation" },
  { slug: "osteoporosis-risk", category: "womens_health",
    text: "Women lose bone density rapidly in the years around menopause, and about one in two women over 50 will break a bone because of osteoporosis. Weight-bearing and resistance training is the best-supported prevention there is.",
    source: "International Osteoporosis Foundation" },
  { slug: "iron-women", category: "womens_health",
    text: "Iron deficiency is far more common in menstruating women than in men, and low iron shows up as training fatigue long before anything else. Persistent unexplained tiredness in training is worth a blood test.",
    source: "American Journal of Clinical Nutrition" },
  { slug: "cycle-training", category: "womens_health",
    text: "Some women feel noticeably stronger in the first half of their cycle and flatter in the days before their period. The evidence for rigid cycle-based programming is weak, but tracking how you feel and adjusting is entirely reasonable.",
    source: "McNulty et al., Sports Medicine, 2020" },
  { slug: "pelvic-floor", category: "womens_health",
    text: "Leaking during jumping or heavy lifting is common but not something to just live with — it usually responds well to targeted pelvic floor work. It's worth raising with a physio rather than quietly avoiding exercises.",
    source: "International Urogynecology Journal" },
  { slug: "strength-and-menopause", category: "womens_health",
    text: "The muscle and bone you build before menopause is the buffer you draw down during it. Starting in your thirties is genuinely the highest-leverage timing there is.",
    source: "Journal of Mid-Life Health" },

  // ── Motivation ────────────────────────────────────────────────────────────
  { slug: "consistency-over-intensity", category: "motivation",
    text: "Three good sessions a week for a year beats six perfect ones a week for a month. Nearly everyone who succeeds at this does so by being boringly consistent, not by being impressive.",
    source: "Adherence research" },
  { slug: "habit-formation", category: "motivation",
    text: "New habits took a median of 66 days to feel automatic in one well-known study — and missing a single day had no measurable effect on forming the habit. One skipped workout doesn't break anything.",
    source: "Lally et al., European Journal of Social Psychology, 2010" },
  { slug: "exercise-mood", category: "motivation",
    text: "A single session of moderate exercise reliably improves mood and reduces anxiety, usually within minutes of finishing. On the days you least want to train, that's the effect you're actually buying.",
    source: "Basso & Suzuki, Brain Plasticity, 2017" },
  { slug: "exercise-depression", category: "motivation",
    text: "Regular exercise is associated with substantially lower risk of developing depression, and it works as a treatment as well as a preventative. It's one of the best-evidenced mental health interventions that exists.",
    source: "Schuch et al., American Journal of Psychiatry, 2018" },
  { slug: "identity-shift", category: "motivation",
    text: "People who stick with training long-term tend to shift from 'I'm trying to lose weight' to 'I'm someone who trains.' The goal gets you started; the identity is what keeps going after you hit it.",
    source: "Behavioral psychology" },
  { slug: "scale-is-one-signal", category: "motivation",
    text: "Strength gained, clothes fitting differently, stairs feeling easier, and sleeping better are all real progress the scale can't see. Judging a good month by one number throws away most of the evidence.",
    source: "Body composition research" },
  { slug: "restart-cost", category: "motivation",
    text: "The hardest part of coming back after a break is almost always psychological, not physical. Your body picks up faster than your confidence does — expect the first session back to feel worse than it is.",
    source: "Detraining research" },
];
