type FactSeed = {
  slug: string;
  category: "sedentary_risk" | "strength" | "nutrition" | "recovery" | "motivation" | "womens_health";
  text: string;
  source?: string;
};

/**
 * Facts the coach can drop in when they connect to what she just did. Written
 * to be true and useful rather than alarming — each one should change a
 * decision, not just impress.
 */
export const FACTS: FactSeed[] = [
  // ── The cost of sitting ───────────────────────────────────────────────────
  { slug: "sitting-mortality", category: "sedentary_risk",
    text: "Long uninterrupted sitting is linked to higher all-cause mortality, and it's a separate risk from not exercising. A pooled analysis of over a million people found that roughly 60–75 minutes of daily moderate activity largely offsets the risk of even 8 hours of sitting.",
    source: "Ekelund et al., The Lancet, 2016" },
  { slug: "sitting-glucose", category: "sedentary_risk",
    text: "Breaking up sitting with just 2 minutes of light walking every 20–30 minutes measurably lowers the blood sugar and insulin spikes that follow a meal. The interruption matters more than the intensity.",
    source: "Dunstan et al., Diabetes Care, 2012" },
  { slug: "standing-desk-myth", category: "sedentary_risk",
    text: "A standing desk on its own does surprisingly little. What the research keeps pointing at is movement — changing position and walking a few minutes an hour — not the posture you hold still in.",
    source: "Cochrane review, 2018" },
  { slug: "sitting-hip-flexors", category: "sedentary_risk",
    text: "Hours of sitting keeps the hip flexors in a shortened position, which quietly tilts the pelvis and makes the glutes lazier at doing their job. It's a major reason desk workers feel tight in the lower back and weak in the hips.",
    source: "Journal of Physical Therapy Science" },
  { slug: "sedentary-back-pain", category: "sedentary_risk",
    text: "For chronic low back pain, exercise beats rest in essentially every high-quality trial. Movement is the treatment, not the risk.",
    source: "JAMA Internal Medicine, 2016" },
  { slug: "vo2max-mortality", category: "sedentary_risk",
    text: "In a study of over 122,000 people, cardiorespiratory fitness predicted survival more strongly than smoking, diabetes, or high blood pressure. Being unfit carried a greater risk than any of the traditional risk factors measured.",
    source: "Mandsager et al., JAMA Network Open, 2018" },
  { slug: "steps-mortality", category: "sedentary_risk",
    text: "Mortality risk drops steeply as daily steps rise from about 3,000 to 7,000, then flattens out. You don't need 10,000 — you need to not be at 3,000.",
    source: "Paluch et al., JAMA Network Open, 2021" },
  { slug: "sitting-circulation", category: "sedentary_risk",
    text: "An hour of uninterrupted sitting measurably reduces blood flow in the leg arteries — and a 5-minute walk restores it completely. The damage isn't cumulative if you interrupt it.",
    source: "Thosar et al., Medicine & Science in Sports & Exercise, 2015" },
  { slug: "exercise-cognition", category: "sedentary_risk",
    text: "Regular aerobic exercise is associated with larger hippocampal volume and better memory in adults. Sedentary time works the other direction.",
    source: "Erickson et al., PNAS, 2011" },

  { slug: "movement-snacks", category: "sedentary_risk",
    text: "The old ten-minute minimum is gone — the WHO's 2020 guidelines count every bout of movement toward your weekly total, however short. A flight of stairs and a walk to the bins are not rounding errors.",
    source: "WHO Physical Activity Guidelines, 2020" },
  { slug: "vilpa", category: "sedentary_risk",
    text: "Short bursts of hard everyday effort — carrying shopping upstairs, a fast walk to catch a bus — are linked to meaningfully lower cardiovascular risk even in people who never formally exercise. Three or four one-minute bursts a day is roughly the dose the data points at.",
    source: "Stamatakis et al., Nature Medicine, 2022" },
  { slug: "training-doesnt-cancel-sitting", category: "sedentary_risk",
    text: "Three sessions a week doesn't cancel out ten hours a day of sitting; they're separate exposures with separate effects on health. You need the training and the movement scattered through the day — one isn't payment for the other.",
    source: "Sedentary behaviour epidemiology" },
  { slug: "blood-pressure-exercise", category: "sedentary_risk",
    text: "Regular aerobic exercise lowers resting systolic blood pressure by roughly 5–8 mmHg in people with elevated readings — comparable to what a first-line medication does. Very few things you can do for free move a clinical number that much.",
    source: "ACC/AHA hypertension guideline" },
  { slug: "exercise-osteoarthritis", category: "sedentary_risk",
    text: "Exercise, including strength training, is a first-line treatment for knee osteoarthritis in every major guideline. The intuition that loading wears a joint out has it backwards — cartilage and the muscles around the joint both need load to stay healthy.",
    source: "NICE and OARSI osteoarthritis guidelines" },
  { slug: "strength-injury-prevention", category: "sedentary_risk",
    text: "Strength training reduces injury risk by roughly a third, and overuse injuries by close to half. Stretching, in the same analysis, barely moved the needle — being strong is the protection, not being bendy.",
    source: "Lauersen et al., British Journal of Sports Medicine, 2014" },

  // ── Strength ──────────────────────────────────────────────────────────────
  { slug: "muscle-decline-30", category: "strength",
    text: "From your thirties onward, adults lose roughly 3–8% of muscle mass per decade without resistance training — and the rate accelerates after 60. Lifting is the only intervention that reliably reverses it.",
    source: "Volpi et al., Clinical Nutrition, 2004" },
  { slug: "strength-mortality", category: "strength",
    text: "Strength training twice a week is associated with lower all-cause mortality, independent of how much cardio you do. Two sessions is the point where the curve bends.",
    source: "Momma et al., British Journal of Sports Medicine, 2022" },
  { slug: "grip-strength", category: "strength",
    text: "Grip strength predicts cardiovascular mortality better than systolic blood pressure does. It's a proxy for total body strength — which is a proxy for how well you're aging.",
    source: "Leong et al., The Lancet (PURE study), 2015" },
  { slug: "neural-gains", category: "strength",
    text: "Most of your strength gain in the first 4–6 weeks isn't new muscle — it's your nervous system learning to recruit what you already have. That's why beginners improve so fast, and why those early jumps are real even before anything looks different.",
    source: "Sale, Medicine & Science in Sports & Exercise" },
  { slug: "progressive-overload", category: "strength",
    text: "Muscle adapts to demand and then stops. Progressive overload — a rep more, a pound more, a better-controlled tempo — is the entire mechanism. Doing the same workout for months is maintenance, not progress.",
    source: "Principle of progressive overload" },
  { slug: "detraining", category: "strength",
    text: "Strength holds up for about three to four weeks without training. One missed session is statistically nothing — the fitness you built doesn't evaporate because of a bad week.",
    source: "Mujika & Padilla, Sports Medicine, 2000" },
  { slug: "muscle-memory", category: "strength",
    text: "Muscle cells keep the extra nuclei they gained from previous training, possibly permanently. Rebuilding lost muscle is genuinely faster than building it the first time — the work you've already done isn't wasted.",
    source: "Gundersen, Journal of Experimental Biology, 2016" },
  { slug: "muscle-calories-myth", category: "strength",
    text: "A pound of muscle burns about 6 calories a day at rest, not the 50 you'll see repeated online. Muscle is worth building for strength, glucose control, bone density, and shape — the metabolic bump is a bonus, not the reason.",
    source: "Wang et al., American Journal of Clinical Nutrition, 2010" },
  { slug: "rest-between-sets", category: "strength",
    text: "For strength on compound lifts, 2–3 minutes between sets produces better results than 1 minute. Cutting rest short to save time mostly just makes the next set worse.",
    source: "Schoenfeld et al., Journal of Strength & Conditioning Research, 2016" },
  { slug: "compound-first", category: "strength",
    text: "Do the exercise that matters most first, while you're fresh. Squats after twenty minutes of arm work are a worse squat session — order is a training variable.",
    source: "Exercise order research, ACSM" },
  { slug: "form-before-load", category: "strength",
    text: "Adding weight to a movement pattern you can't yet control just makes the flawed pattern stronger. Own the technique at a weight that feels easy, then climb.",
    source: "Coaching principle" },
  { slug: "unilateral-imbalance", category: "strength",
    text: "Single-leg and single-arm work exposes side-to-side imbalances that barbell lifts happily hide. That's a feature — imbalances you can see are imbalances you can fix.",
    source: "Journal of Strength & Conditioning Research" },
  { slug: "insulin-sensitivity", category: "strength",
    text: "A single resistance training session improves insulin sensitivity for up to 24 hours afterward. Muscle is where most of your blood glucose gets stored — more of it means better handling of every meal.",
    source: "Holten et al., Diabetes, 2004" },

  { slug: "rep-ranges", category: "strength",
    text: "Sets of 5 and sets of 25 build similar amounts of muscle when both are taken close to failure. Heavier reps build more maximal strength, but the muscle comes from the effort, not from a magic number.",
    source: "Resistance training meta-analyses (Schoenfeld and colleagues)" },
  { slug: "reps-in-reserve", category: "strength",
    text: "You don't have to train to failure. Stopping one to three reps short produces nearly the same growth with far less fatigue — which means the next set, and the next session, are both better.",
    source: "Meta-analyses of training to failure" },
  { slug: "weekly-sets", category: "strength",
    text: "Growth tracks with hard sets per muscle per week, with most of the benefit arriving somewhere around 10–20. Below about four sets a week you're maintaining, which is a perfectly good goal — just not the same one.",
    source: "Resistance training volume research" },
  { slug: "training-frequency", category: "strength",
    text: "The same weekly sets spread over two or three sessions beat cramming them into one. Three full-body days is a better use of your week than one long everything-day.",
    source: "Schoenfeld et al., Sports Medicine, 2016" },
  { slug: "full-range-of-motion", category: "strength",
    text: "Full range of motion builds more muscle than partial reps at the same load, and the stretched half of the rep seems to do most of that work. Lighter and complete beats heavier and half.",
    source: "Range-of-motion research in resistance training" },
  { slug: "eccentric-control", category: "strength",
    text: "The lowering half of a rep produces more force than the lifting half and drives a large share of the adaptation. Two or three seconds down is free progress most people throw away.",
    source: "Eccentric training research" },
  { slug: "static-stretch-before-lifting", category: "strength",
    text: "Long static stretches immediately before lifting temporarily reduce strength and power. Warm up by moving; save the long holds for after the session or a separate slot.",
    source: "Reviews of acute static stretching and performance" },
  { slug: "warmup-sets", category: "strength",
    text: "Two or three progressively heavier sets before your working weight raise muscle temperature and rehearse the pattern. They cost about four minutes and make the working sets both safer and stronger.",
    source: "Warm-up research, ACSM" },
  { slug: "deload-weeks", category: "strength",
    text: "Cutting volume for a week every month or two lets accumulated fatigue clear while the fitness stays. Planned easy weeks are how you avoid unplanned ones.",
    source: "Periodisation practice" },
  { slug: "quad-strength-knee", category: "strength",
    text: "Quadriceps strength is one of the strongest modifiable predictors of knee pain and function. A knee that dislikes load usually needs a stronger leg, built in the range it tolerates, more than it needs rest.",
    source: "Knee osteoarthritis and patellofemoral pain research" },

  // ── Nutrition ─────────────────────────────────────────────────────────────
  { slug: "protein-threshold", category: "nutrition",
    text: "Benefits for building and keeping muscle plateau around 1.6 g of protein per kg of body weight per day. Beyond that, extra protein mostly just costs money.",
    source: "Morton et al., British Journal of Sports Medicine, 2018" },
  { slug: "protein-during-deficit", category: "nutrition",
    text: "Dieting without enough protein or resistance training means roughly a quarter of the weight you lose is muscle rather than fat. Protein plus lifting is what makes it fat you're losing.",
    source: "Cava et al., Advances in Nutrition, 2017" },
  { slug: "protein-satiety", category: "nutrition",
    text: "Protein is the most filling macronutrient per calorie, and it costs 20–30% of its own calories just to digest — versus about 5% for fat. High protein makes a deficit easier to actually hold.",
    source: "Halton & Hu, Journal of the American College of Nutrition, 2004" },
  { slug: "deficit-size", category: "nutrition",
    text: "Losing more than about 1% of body weight per week increasingly costs muscle and gets harder to sustain. Slower loss keeps more of the weight off afterward — this is one place where being impatient loses.",
    source: "Garthe et al., International Journal of Sport Nutrition, 2011" },
  { slug: "fiber-satiety", category: "nutrition",
    text: "Most adults eat around half the fiber they need. Fiber slows digestion, blunts blood sugar spikes, and keeps you full — it's the cheapest appetite management available.",
    source: "Dietary Guidelines for Americans" },
  { slug: "liquid-calories", category: "nutrition",
    text: "Calories you drink barely register as food to your appetite system — you don't eat less later to compensate. It's the single easiest place to find a few hundred calories.",
    source: "Mattes, Physiology & Behavior, 2006" },
  { slug: "water-weight", category: "nutrition",
    text: "Body weight swings 2–4 lb day to day from water, sodium, glycogen, and digestion. A single weigh-in is noise; the direction across two weeks is the signal.",
    source: "Body composition measurement research" },
  { slug: "glycogen-water", category: "nutrition",
    text: "Every gram of stored carbohydrate holds about 3 grams of water. That's why a low-carb day drops the scale fast and a pasta dinner puts it back — neither is fat.",
    source: "Kreitzman et al., American Journal of Clinical Nutrition, 1992" },
  { slug: "spot-reduction", category: "nutrition",
    text: "You can't choose where fat comes off. Crunches build the muscle underneath but don't burn the fat above it — where you lose from is genetics and hormones, and it evens out over time.",
    source: "Ramírez-Campillo et al., Journal of Strength & Conditioning Research, 2013" },
  { slug: "neat", category: "nutrition",
    text: "Non-exercise movement — fidgeting, pacing, taking the stairs — can differ by hundreds of calories a day between two similar people. Deficits often stall because this quietly drops, not because metabolism broke.",
    source: "Levine et al., Science, 1999" },
  { slug: "alcohol-recovery", category: "nutrition",
    text: "Alcohol after training suppresses muscle protein synthesis by roughly a third, even when protein is eaten alongside it. It's not forbidden — it's just worth knowing what it costs.",
    source: "Parr et al., PLOS ONE, 2014" },
  { slug: "meal-timing", category: "nutrition",
    text: "Total daily protein and calories matter far more than exact timing. The 'anabolic window' is more like several hours than thirty minutes — you don't have to sprint to a shaker.",
    source: "Schoenfeld et al., Journal of the International Society of Sports Nutrition, 2013" },
  { slug: "adherence-beats-diet", category: "nutrition",
    text: "Head-to-head trials of low-carb, low-fat, and everything between keep finding the same thing: the diet people stick to is the one that works. There's no metabolic trick that beats adherence.",
    source: "Gardner et al., JAMA, 2018" },

  { slug: "intake-underreporting", category: "nutrition",
    text: "People under-report what they eat by 20–50% without meaning to, and confidence about it is a poor guide to accuracy. If a deficit isn't working, weighing food for one honest week usually explains it.",
    source: "Lichtman et al., New England Journal of Medicine, 1992" },
  { slug: "ultra-processed-intake", category: "nutrition",
    text: "When people were fed matched meals in a metabolic ward and told to eat as much as they liked, the ultra-processed version led to about 500 extra calories a day — with the macros matched on paper. How food is made matters beyond what's in it.",
    source: "Hall et al., Cell Metabolism, 2019" },
  { slug: "protein-distribution", category: "nutrition",
    text: "Spreading protein over three or four meals of roughly 30–40 g beats a token breakfast and an enormous dinner for building muscle. Same daily total, better result — this is one of the few places where timing genuinely matters.",
    source: "Protein distribution research" },
  { slug: "creatine", category: "nutrition",
    text: "Creatine monohydrate is the most studied supplement in sport: 3–5 g a day, cheap, and it works in women as well as men. The bloating and hair-loss stories aren't supported by the evidence.",
    source: "International Society of Sports Nutrition position stand" },
  { slug: "hydration-performance", category: "nutrition",
    text: "Losing about 2% of body weight in fluid measurably reduces strength and endurance and makes a session feel harder than it is. Thirst is a late signal — drink across the day, not just during training.",
    source: "American College of Sports Medicine position stand" },
  { slug: "fasted-cardio", category: "nutrition",
    text: "Training fasted burns more fat during the session and less afterward, and the 24-hour total comes out about the same. Do it if it suits your stomach, not because it burns more.",
    source: "Schoenfeld et al., Journal of the International Society of Sports Nutrition, 2014" },
  { slug: "eating-rate", category: "nutrition",
    text: "Fullness signals take around 20 minutes to arrive, so eating fast reliably means eating more before they land. Slowing a meal down is one of the very few appetite tools that costs nothing.",
    source: "Appetite and satiety research" },
  { slug: "activity-and-maintenance", category: "nutrition",
    text: "People who lose weight and keep it off for years average around an hour of activity a day. Diet does most of the losing; activity does most of the keeping off.",
    source: "National Weight Control Registry" },

  { slug: "waist-vs-bmi", category: "nutrition",
    text: "Waist circumference predicts cardiovascular and diabetes risk better than BMI does, because it reflects visceral fat around the organs rather than total mass. A tape measure tells you something the scale genuinely cannot.",
    source: "Ross et al., Nature Reviews Endocrinology, 2020" },
  { slug: "waist-target-women", category: "womens_health",
    text: "For women, a waist under about 35 inches (88cm) is the usual threshold for meaningfully lower metabolic risk. It's a better weekly target than a scale number, and it moves for reasons you control.",
    source: "World Health Organization / NIH guidance" },
  { slug: "recomposition", category: "strength",
    text: "Beginners returning to lifting often build muscle and lose fat at the same time. The scale barely moves for weeks while clothes fit differently and the waist drops — that's body recomposition, not a stall, and it's one of the best things that can happen early on.",
    source: "Barakat et al., Strength & Conditioning Journal, 2020" },
  { slug: "measure-consistently", category: "motivation",
    text: "Measure at the same time of day, ideally first thing before eating, and the same day each week. Most week-to-week measurement noise is tape placement and hydration rather than any real change.",
    source: "Body composition measurement practice" },

  // ── Recovery ──────────────────────────────────────────────────────────────
  { slug: "sleep-fat-loss", category: "recovery",
    text: "Dieters sleeping 5.5 hours instead of 8.5 lost the same total weight — but 55% less of it was fat, and more of it was muscle. Sleep decides what kind of weight comes off.",
    source: "Nedeltcheva et al., Annals of Internal Medicine, 2010" },
  { slug: "sleep-hunger", category: "recovery",
    text: "One short night raises ghrelin and lowers leptin, which is a hormonal way of saying you'll be hungrier tomorrow and it isn't a willpower failure.",
    source: "Spiegel et al., Annals of Internal Medicine, 2004" },
  { slug: "doms-not-a-metric", category: "recovery",
    text: "Soreness peaks 24–72 hours after a session and tracks how unfamiliar the movement was, not how effective it was. Some of the best training weeks leave you barely sore.",
    source: "Cheung et al., Sports Medicine, 2003" },
  { slug: "rest-days-build", category: "recovery",
    text: "Training is the stimulus; the adaptation happens while you rest. Rest days aren't time off from progress — they're when the progress is actually made.",
    source: "Supercompensation principle" },
  { slug: "walking-recovery", category: "recovery",
    text: "Easy walking on rest days increases blood flow to sore muscles and tends to reduce soreness rather than add to it. Recovery is usually active, not motionless.",
    source: "Dupuy et al., Frontiers in Physiology, 2018" },
  { slug: "stress-recovery", category: "recovery",
    text: "High life stress measurably slows recovery from training — the same workout takes longer to bounce back from during a hard week. Scaling back during a rough patch is strategy, not weakness.",
    source: "Stults-Kolehmainen & Bartholomew, Medicine & Science in Sports & Exercise, 2012" },
  { slug: "exercise-sleep-quality", category: "recovery",
    text: "Regular exercise improves both how fast you fall asleep and how deeply you sleep — and better sleep makes the next session better. It compounds in both directions.",
    source: "Kredlow et al., Journal of Behavioral Medicine, 2015" },

  { slug: "sleep-duration-target", category: "recovery",
    text: "Seven to nine hours is the adult recommendation in every major guideline, and most people who function on five have simply stopped noticing they're impaired. Sleep is the highest-leverage recovery tool you have, and it's free.",
    source: "American Academy of Sleep Medicine" },
  { slug: "caffeine-half-life", category: "recovery",
    text: "Caffeine has a half-life of about five hours, and in a controlled trial 400 mg taken six hours before bed still cut measured sleep by roughly an hour. The afternoon coffee costs you a night you won't connect it to.",
    source: "Drake et al., Journal of Clinical Sleep Medicine, 2013" },
  { slug: "sleep-extension", category: "recovery",
    text: "Athletes who deliberately extend sleep get faster and more accurate — real performance gains from no extra training. Sleep is a training input, not just the absence of activity.",
    source: "Sleep extension research in athletes" },
  { slug: "alcohol-sleep", category: "recovery",
    text: "Alcohol gets you to sleep faster and makes the sleep much worse, suppressing REM and fragmenting the second half of the night. That's why a night out tends to cost the next two training days rather than one.",
    source: "Sleep research on alcohol" },
  { slug: "sleep-and-injury", category: "recovery",
    text: "Athletes sleeping under about eight hours get injured noticeably more often. Fatigue shows up as sloppy technique long before it shows up as feeling tired.",
    source: "Sleep and injury research in athletes" },
  { slug: "foam-rolling", category: "recovery",
    text: "Foam rolling and massage give a modest, short-lived reduction in soreness and don't harm adaptation. Feeling better is a real thing to want — it just isn't a substitute for sleep and food.",
    source: "Meta-analyses of recovery modalities" },
  { slug: "cold-water-immersion", category: "recovery",
    text: "Regular cold-water immersion straight after lifting appears to blunt part of the muscle-building signal. Use it to feel better before something that matters, not as a habit after strength work.",
    source: "Post-exercise cold water immersion research" },

  // ── Women's health ────────────────────────────────────────────────────────
  { slug: "women-bulking-myth", category: "womens_health",
    text: "Women produce roughly a fifteenth of the testosterone men do, which is why lifting heavy builds strength and shape rather than bulk. The look people actually want almost always requires more muscle, not less.",
    source: "Endocrine physiology" },
  { slug: "peak-bone-mass", category: "womens_health",
    text: "Peak bone mass is reached around age 30, and resistance training is one of the few things that meaningfully builds and preserves it afterward. Loading bone in your thirties is a deposit against your sixties.",
    source: "National Osteoporosis Foundation" },
  { slug: "osteoporosis-risk", category: "womens_health",
    text: "Women lose bone density rapidly in the years around menopause, and about one in two women over 50 will break a bone because of osteoporosis. Weight-bearing and resistance training is the best-supported prevention there is.",
    source: "International Osteoporosis Foundation" },
  { slug: "iron-women", category: "womens_health",
    text: "Iron deficiency is far more common in menstruating women than in men, and low iron shows up as training fatigue long before anything else. Persistent unexplained tiredness in training is worth a blood test.",
    source: "American Journal of Clinical Nutrition" },
  { slug: "cycle-training", category: "womens_health",
    text: "Some women feel noticeably stronger in the first half of their cycle and flatter in the days before their period. The evidence for rigid cycle-based programming is weak, but tracking how you feel and adjusting is entirely reasonable.",
    source: "McNulty et al., Sports Medicine, 2020" },
  { slug: "pelvic-floor", category: "womens_health",
    text: "Leaking during jumping or heavy lifting is common but not something to just live with — it usually responds well to targeted pelvic floor work. It's worth raising with a physio rather than quietly avoiding exercises.",
    source: "International Urogynecology Journal" },
  { slug: "strength-and-menopause", category: "womens_health",
    text: "The muscle and bone you build before menopause is the buffer you draw down during it. Starting in your thirties is genuinely the highest-leverage timing there is.",
    source: "Journal of Mid-Life Health" },

  { slug: "bone-needs-load", category: "womens_health",
    text: "Bone responds to load and impact, not to time spent moving. Swimming and cycling are excellent for the heart and do close to nothing for bone density — that job belongs to lifting and weight-bearing work.",
    source: "Bone loading research" },
  { slug: "heavy-load-builds-bone", category: "womens_health",
    text: "In a trial of postmenopausal women with low bone mass, twice-weekly heavy resistance and impact training improved spine and hip bone density, while a light supervised programme didn't. For bone, the load has to be meaningful.",
    source: "LIFTMOR trial, Journal of Bone and Mineral Research, 2018" },
  { slug: "calcium-intake-women", category: "womens_health",
    text: "Women aged 19–50 are advised to get around 1,000 mg of calcium a day, and most fall short. Food first — dairy, tinned fish with bones, fortified alternatives, leafy greens — with supplements as the backstop.",
    source: "NIH Office of Dietary Supplements" },
  { slug: "women-strength-response", category: "womens_health",
    text: "Women gain strength at roughly the same relative rate as men and tend to recover from resistance training at least as well. There's no separate women's training that works better — the same principles apply, at the same intensities.",
    source: "Sex differences in resistance training research" },
  { slug: "sports-bra", category: "womens_health",
    text: "Breast movement during running and jumping is measured in centimetres in every direction, and a properly fitted high-support bra measurably reduces both movement and pain. It's equipment, not a comfort preference.",
    source: "Breast biomechanics research" },
  { slug: "womens-heart-disease", category: "womens_health",
    text: "Heart disease is the leading cause of death in women, and risk climbs in the years after menopause. The lifting and the walking are cardiovascular prevention as much as they're body composition work.",
    source: "American Heart Association" },

  // ── Motivation ────────────────────────────────────────────────────────────
  { slug: "consistency-over-intensity", category: "motivation",
    text: "Three good sessions a week for a year beats six perfect ones a week for a month. Nearly everyone who succeeds at this does so by being boringly consistent, not by being impressive.",
    source: "Adherence research" },
  { slug: "habit-formation", category: "motivation",
    text: "New habits took a median of 66 days to feel automatic in one well-known study — and missing a single day had no measurable effect on forming the habit. One skipped workout doesn't break anything.",
    source: "Lally et al., European Journal of Social Psychology, 2010" },
  { slug: "exercise-mood", category: "motivation",
    text: "A single session of moderate exercise reliably improves mood and reduces anxiety, usually within minutes of finishing. On the days you least want to train, that's the effect you're actually buying.",
    source: "Basso & Suzuki, Brain Plasticity, 2017" },
  { slug: "exercise-depression", category: "motivation",
    text: "Regular exercise is associated with substantially lower risk of developing depression, and it works as a treatment as well as a preventative. It's one of the best-evidenced mental health interventions that exists.",
    source: "Schuch et al., American Journal of Psychiatry, 2018" },
  { slug: "identity-shift", category: "motivation",
    text: "People who stick with training long-term tend to shift from 'I'm trying to lose weight' to 'I'm someone who trains.' The goal gets you started; the identity is what keeps going after you hit it.",
    source: "Behavioral psychology" },
  { slug: "scale-is-one-signal", category: "motivation",
    text: "Strength gained, clothes fitting differently, stairs feeling easier, and sleeping better are all real progress the scale can't see. Judging a good month by one number throws away most of the evidence.",
    source: "Body composition research" },
  { slug: "restart-cost", category: "motivation",
    text: "The hardest part of coming back after a break is almost always psychological, not physical. Your body picks up faster than your confidence does — expect the first session back to feel worse than it is.",
    source: "Detraining research" },
  { slug: "implementation-intentions", category: "motivation",
    text: "Deciding in advance exactly when and where — 'Tuesday, 7am, in the spare room' — substantially raises follow-through compared with intending to train more. The plan does work that willpower doesn't have to.",
    source: "Gollwitzer & Sheeran, implementation intentions meta-analysis, 2006" },
  { slug: "never-miss-twice", category: "motivation",
    text: "One skipped session is weather. Two in a row is where a habit starts to come unpicked. The thing to protect isn't a perfect record, it's the gap between misses.",
    source: "Habit research, applied" },
  { slug: "self-compassion-lapse", category: "motivation",
    text: "After a lapse, people who are kind to themselves get back to the routine faster than people who are harsh with themselves. Guilt feels like accountability and behaves like avoidance.",
    source: "Self-compassion and behaviour change research" },
  { slug: "minimum-viable-session", category: "motivation",
    text: "On a bad day, a short easy session protects the habit and costs almost nothing. Fifteen minutes done beats forty-five skipped, mostly because it saves you from having to restart.",
    source: "Adherence practice" },
  { slug: "resistance-training-mood", category: "motivation",
    text: "Resistance training specifically — not only cardio — reduces depressive symptoms in randomised trials, including in people whose strength didn't measurably improve. The mood effect isn't downstream of the results.",
    source: "Gordon et al., JAMA Psychiatry, 2018" },
  { slug: "log-your-sets", category: "motivation",
    text: "Written logs beat memory by a wide margin, and seeing last week's numbers is what makes progressive overload actually happen. The log isn't admin — it's the mechanism.",
    source: "Self-monitoring research in behaviour change" },
];
