/**
 * Food macro library, seeded as reference data like the exercise library.
 *
 * Everything is per 100g (per 100ml for drinks — near enough for anything
 * poured), because that is how labels are written and how a kitchen scale
 * works. The lookup scales from there using `unitGrams` when she types a
 * portion rather than a weight: "two slices of bread", "one egg".
 *
 * Rules the data keeps to:
 * • Cooked weights for anything weighed after cooking — meat, pasta, rice —
 *   because that is when it goes on the scale. The name always says which.
 * • Carbohydrate is available carbohydrate, the UK label convention: fibre is
 *   listed separately and is not counted twice. So 4×protein + 4×carbs +
 *   9×fat lands within about 10% of the stated calories on every row.
 *   The residue is fibre, which carries roughly 2 kcal/g and is not in that
 *   sum, and alcohol, which carries 7 and has no column of its own.
 * • Values follow standard reference tables (USDA, McCance & Widdowson) or,
 *   for shop-bought things those tables do not cover, the middle of the
 *   supermarket range. Nothing here is a guess — a food we could not pin
 *   down was left out so the coach estimates it instead of the table lying.
 * • `aliases` carry the other word for the same thing, in both dialects, so
 *   "aubergine" finds "eggplant" and "mince" finds "ground beef".
 */

export type FoodCategory =
  | "meat" | "fish" | "dairy" | "eggs" | "grain" | "legume" | "vegetable"
  | "fruit" | "nut" | "fat" | "sauce" | "drink" | "snack" | "prepared";

export type FoodSeed = {
  slug: string;
  name: string;
  category: FoodCategory;
  /** Per 100g, always. */
  kcal: number;
  proteinG: number;
  /** Available carbohydrate — fibre is not included here. */
  carbsG: number;
  fatG: number;
  /** Null where it is negligible or not meaningfully measured. */
  fibreG: number | null;
  /** Grams in one natural unit; null where there is no natural unit. */
  unitGrams: number | null;
  unitLabel: string | null;
  aliases: string[];
};

export const FOODS: FoodSeed[] = [
  // ── Meat and poultry ──────────────────────────────────────────────────────
  { slug: "chicken-breast-cooked", name: "Chicken breast, cooked", category: "meat", kcal: 165, proteinG: 31, carbsG: 0, fatG: 3.6, fibreG: null, unitGrams: 120, unitLabel: "breast", aliases: ["chicken", "grilled chicken", "skinless chicken breast", "chicken fillet"] },
  { slug: "chicken-breast-raw", name: "Chicken breast, raw", category: "meat", kcal: 120, proteinG: 22.5, carbsG: 0, fatG: 2.6, fibreG: null, unitGrams: 160, unitLabel: "breast", aliases: ["raw chicken breast", "uncooked chicken"] },
  { slug: "chicken-thigh-cooked", name: "Chicken thigh, skinless, cooked", category: "meat", kcal: 209, proteinG: 26, carbsG: 0, fatG: 11, fibreG: null, unitGrams: 75, unitLabel: "thigh", aliases: ["chicken thighs", "boneless chicken thigh"] },
  { slug: "chicken-thigh-skin-on-roasted", name: "Chicken thigh, skin on, roasted", category: "meat", kcal: 229, proteinG: 25, carbsG: 0, fatG: 14.5, fibreG: null, unitGrams: 90, unitLabel: "thigh", aliases: ["roast chicken thigh"] },
  { slug: "chicken-drumstick-cooked", name: "Chicken drumstick, skinless, cooked", category: "meat", kcal: 175, proteinG: 28, carbsG: 0, fatG: 5.7, fibreG: null, unitGrams: 70, unitLabel: "drumstick", aliases: ["chicken leg"] },
  { slug: "chicken-wing-cooked", name: "Chicken wing, roasted", category: "meat", kcal: 290, proteinG: 27, carbsG: 0, fatG: 19.5, fibreG: null, unitGrams: 34, unitLabel: "wing", aliases: ["chicken wings"] },
  { slug: "rotisserie-chicken", name: "Rotisserie chicken, meat only", category: "meat", kcal: 190, proteinG: 29, carbsG: 0, fatG: 8, fibreG: null, unitGrams: 150, unitLabel: "portion", aliases: ["roast chicken", "shop-bought roast chicken", "cooked chicken", "supermarket chicken"] },
  { slug: "chicken-mince-cooked", name: "Chicken mince, cooked", category: "meat", kcal: 189, proteinG: 27, carbsG: 0, fatG: 8.5, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["ground chicken", "minced chicken"] },
  { slug: "turkey-breast-cooked", name: "Turkey breast, cooked", category: "meat", kcal: 135, proteinG: 30, carbsG: 0, fatG: 1, fibreG: null, unitGrams: 130, unitLabel: "portion", aliases: ["turkey", "roast turkey", "turkey steak"] },
  { slug: "turkey-mince-cooked", name: "Turkey mince, lean, cooked", category: "meat", kcal: 190, proteinG: 28, carbsG: 0, fatG: 8.5, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["ground turkey", "minced turkey"] },
  { slug: "turkey-rashers", name: "Turkey rashers, grilled", category: "meat", kcal: 120, proteinG: 17, carbsG: 2, fatG: 4.5, fibreG: null, unitGrams: 12, unitLabel: "rasher", aliases: ["turkey bacon", "turkey rasher"] },
  { slug: "beef-mince-5-cooked", name: "Beef mince, 5% fat, cooked", category: "meat", kcal: 174, proteinG: 26, carbsG: 0, fatG: 7.4, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["beef", "lean ground beef", "extra lean mince", "5% beef mince", "95% lean beef"] },
  { slug: "beef-mince-5-raw", name: "Beef mince, 5% fat, raw", category: "meat", kcal: 137, proteinG: 21.5, carbsG: 0, fatG: 5, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["raw lean mince", "raw ground beef"] },
  { slug: "beef-mince-20-cooked", name: "Beef mince, 20% fat, cooked", category: "meat", kcal: 254, proteinG: 26, carbsG: 0, fatG: 17, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["ground beef", "regular mince", "80/20 beef"] },
  { slug: "sirloin-steak-cooked", name: "Sirloin steak, grilled", category: "meat", kcal: 212, proteinG: 30, carbsG: 0, fatG: 10, fibreG: null, unitGrams: 160, unitLabel: "steak", aliases: ["steak", "beef steak", "minute steak", "strip steak"] },
  { slug: "ribeye-steak-cooked", name: "Ribeye steak, grilled", category: "meat", kcal: 291, proteinG: 25, carbsG: 0, fatG: 21, fibreG: null, unitGrams: 225, unitLabel: "steak", aliases: ["rib-eye", "scotch fillet"] },
  { slug: "fillet-steak-cooked", name: "Fillet steak, grilled", category: "meat", kcal: 218, proteinG: 30, carbsG: 0, fatG: 11, fibreG: null, unitGrams: 170, unitLabel: "steak", aliases: ["beef tenderloin", "filet mignon", "eye fillet"] },
  { slug: "braising-steak-cooked", name: "Braising steak, slow-cooked", category: "meat", kcal: 220, proteinG: 32, carbsG: 0, fatG: 10, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["stewing beef", "chuck steak", "casserole steak"] },
  { slug: "roast-beef-sliced", name: "Roast beef, lean, sliced", category: "meat", kcal: 136, proteinG: 22, carbsG: 1, fatG: 5, fibreG: null, unitGrams: 25, unitLabel: "slice", aliases: ["deli beef", "cold roast beef"] },
  { slug: "corned-beef", name: "Corned beef, tinned", category: "meat", kcal: 250, proteinG: 26, carbsG: 1, fatG: 16, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["bully beef", "canned corned beef"] },
  { slug: "pork-loin-chop-cooked", name: "Pork loin chop, grilled", category: "meat", kcal: 231, proteinG: 27, carbsG: 0, fatG: 13, fibreG: null, unitGrams: 120, unitLabel: "chop", aliases: ["pork chop"] },
  { slug: "pork-tenderloin-cooked", name: "Pork tenderloin, cooked", category: "meat", kcal: 143, proteinG: 26, carbsG: 0, fatG: 3.9, fibreG: null, unitGrams: 150, unitLabel: "portion", aliases: ["pork fillet", "pork loin fillet"] },
  { slug: "pork-mince-cooked", name: "Pork mince, cooked", category: "meat", kcal: 297, proteinG: 26, carbsG: 0, fatG: 21, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["ground pork", "minced pork"] },
  { slug: "bacon-back-grilled", name: "Back bacon, grilled", category: "meat", kcal: 214, proteinG: 25, carbsG: 0, fatG: 13, fibreG: null, unitGrams: 25, unitLabel: "rasher", aliases: ["bacon", "bacon rasher", "canadian bacon"] },
  { slug: "bacon-streaky-cooked", name: "Streaky bacon, cooked", category: "meat", kcal: 541, proteinG: 37, carbsG: 1.4, fatG: 42, fibreG: null, unitGrams: 12, unitLabel: "rasher", aliases: ["american bacon", "side bacon", "crispy bacon"] },
  { slug: "pork-sausage-cooked", name: "Pork sausage, grilled", category: "meat", kcal: 294, proteinG: 18, carbsG: 10, fatG: 20, fibreG: null, unitGrams: 57, unitLabel: "sausage", aliases: ["sausages", "banger"] },
  { slug: "ham-lean-sliced", name: "Ham, lean, sliced", category: "meat", kcal: 107, proteinG: 18, carbsG: 1.5, fatG: 3, fibreG: null, unitGrams: 25, unitLabel: "slice", aliases: ["deli ham", "cooked ham", "lean ham"] },
  { slug: "parma-ham", name: "Parma ham", category: "meat", kcal: 268, proteinG: 27, carbsG: 0, fatG: 17, fibreG: null, unitGrams: 15, unitLabel: "slice", aliases: ["prosciutto", "serrano ham", "cured ham"] },
  { slug: "chorizo", name: "Chorizo", category: "meat", kcal: 455, proteinG: 24, carbsG: 2, fatG: 38, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["spanish sausage"] },
  { slug: "salami", name: "Salami", category: "meat", kcal: 407, proteinG: 22, carbsG: 2, fatG: 33, fibreG: null, unitGrams: 10, unitLabel: "slice", aliases: ["milano salami"] },
  { slug: "pepperoni", name: "Pepperoni", category: "meat", kcal: 494, proteinG: 23, carbsG: 1, fatG: 44, fibreG: null, unitGrams: 5, unitLabel: "slice", aliases: [] },
  { slug: "hot-dog", name: "Hot dog sausage", category: "meat", kcal: 290, proteinG: 10, carbsG: 4, fatG: 26, fibreG: null, unitGrams: 45, unitLabel: "sausage", aliases: ["frankfurter", "wiener"] },
  { slug: "lamb-chop-cooked", name: "Lamb chop, grilled, lean", category: "meat", kcal: 235, proteinG: 30, carbsG: 0, fatG: 13, fibreG: null, unitGrams: 90, unitLabel: "chop", aliases: ["lamb cutlet", "lamb loin chop"] },
  { slug: "lamb-mince-cooked", name: "Lamb mince, cooked", category: "meat", kcal: 283, proteinG: 25, carbsG: 0, fatG: 20, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["ground lamb", "minced lamb"] },
  { slug: "lamb-leg-roast", name: "Roast leg of lamb, lean", category: "meat", kcal: 217, proteinG: 28, carbsG: 0, fatG: 11, fibreG: null, unitGrams: 90, unitLabel: "portion", aliases: ["roast lamb"] },
  { slug: "duck-breast-roasted", name: "Duck breast, skin off, roasted", category: "meat", kcal: 201, proteinG: 23.5, carbsG: 0, fatG: 11, fibreG: null, unitGrams: 140, unitLabel: "breast", aliases: ["duck"] },
  { slug: "venison-cooked", name: "Venison, cooked", category: "meat", kcal: 158, proteinG: 30, carbsG: 0, fatG: 3.2, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["deer meat"] },
  { slug: "beef-jerky", name: "Beef jerky", category: "meat", kcal: 410, proteinG: 33, carbsG: 11, fatG: 25.5, fibreG: null, unitGrams: 28, unitLabel: "bag", aliases: ["biltong", "dried beef"] },

  // ── Fish and seafood ──────────────────────────────────────────────────────
  { slug: "salmon-cooked", name: "Salmon fillet, cooked", category: "fish", kcal: 208, proteinG: 22.5, carbsG: 0, fatG: 12.4, fibreG: null, unitGrams: 130, unitLabel: "fillet", aliases: ["salmon", "baked salmon", "hot-smoked salmon", "grilled salmon"] },
  { slug: "salmon-raw", name: "Salmon fillet, raw", category: "fish", kcal: 183, proteinG: 20, carbsG: 0, fatG: 11, fibreG: null, unitGrams: 150, unitLabel: "fillet", aliases: ["raw salmon", "sashimi salmon"] },
  { slug: "smoked-salmon", name: "Smoked salmon", category: "fish", kcal: 142, proteinG: 25.4, carbsG: 0, fatG: 4.5, fibreG: null, unitGrams: 30, unitLabel: "slice", aliases: ["lox", "cold-smoked salmon"] },
  { slug: "salmon-tinned", name: "Salmon, tinned, drained", category: "fish", kcal: 139, proteinG: 20, carbsG: 0, fatG: 6, fibreG: null, unitGrams: 105, unitLabel: "tin (drained)", aliases: ["canned salmon", "pink salmon"] },
  { slug: "tuna-tinned-water", name: "Tuna, tinned in spring water, drained", category: "fish", kcal: 116, proteinG: 26, carbsG: 0, fatG: 1, fibreG: null, unitGrams: 112, unitLabel: "tin (drained)", aliases: ["tinned tuna", "canned tuna", "tuna in brine", "tuna"] },
  { slug: "tuna-tinned-oil", name: "Tuna, tinned in oil, drained", category: "fish", kcal: 198, proteinG: 29, carbsG: 0, fatG: 8.2, fibreG: null, unitGrams: 112, unitLabel: "tin (drained)", aliases: ["tuna in olive oil"] },
  { slug: "tuna-steak-cooked", name: "Tuna steak, cooked", category: "fish", kcal: 130, proteinG: 29, carbsG: 0, fatG: 1, fibreG: null, unitGrams: 150, unitLabel: "steak", aliases: ["fresh tuna", "yellowfin tuna", "seared tuna"] },
  { slug: "cod-cooked", name: "Cod fillet, cooked", category: "fish", kcal: 105, proteinG: 23, carbsG: 0, fatG: 0.9, fibreG: null, unitGrams: 150, unitLabel: "fillet", aliases: ["cod"] },
  { slug: "cod-raw", name: "Cod fillet, raw", category: "fish", kcal: 82, proteinG: 18, carbsG: 0, fatG: 0.7, fibreG: null, unitGrams: 180, unitLabel: "fillet", aliases: ["raw cod"] },
  { slug: "haddock-cooked", name: "Haddock fillet, cooked", category: "fish", kcal: 112, proteinG: 24, carbsG: 0, fatG: 0.9, fibreG: null, unitGrams: 150, unitLabel: "fillet", aliases: ["haddock"] },
  { slug: "white-fish-cooked", name: "White fish fillet, cooked", category: "fish", kcal: 100, proteinG: 22, carbsG: 0, fatG: 1, fibreG: null, unitGrams: 150, unitLabel: "fillet", aliases: ["white fish", "pollock", "hake", "basa", "coley", "whiting"] },
  { slug: "tilapia-cooked", name: "Tilapia, cooked", category: "fish", kcal: 128, proteinG: 26, carbsG: 0, fatG: 2.7, fibreG: null, unitGrams: 120, unitLabel: "fillet", aliases: [] },
  { slug: "sea-bass-cooked", name: "Sea bass, cooked", category: "fish", kcal: 124, proteinG: 24, carbsG: 0, fatG: 2.6, fibreG: null, unitGrams: 120, unitLabel: "fillet", aliases: ["seabass", "branzino"] },
  { slug: "trout-cooked", name: "Rainbow trout, cooked", category: "fish", kcal: 168, proteinG: 24, carbsG: 0, fatG: 7.2, fibreG: null, unitGrams: 130, unitLabel: "fillet", aliases: ["trout"] },
  { slug: "mackerel-cooked", name: "Mackerel, cooked", category: "fish", kcal: 262, proteinG: 24, carbsG: 0, fatG: 17.8, fibreG: null, unitGrams: 110, unitLabel: "fillet", aliases: ["mackerel"] },
  { slug: "smoked-mackerel", name: "Smoked mackerel", category: "fish", kcal: 354, proteinG: 19, carbsG: 0, fatG: 31, fibreG: null, unitGrams: 80, unitLabel: "fillet", aliases: ["peppered mackerel"] },
  { slug: "sardines-oil", name: "Sardines, tinned in oil, drained", category: "fish", kcal: 208, proteinG: 24.6, carbsG: 0, fatG: 11.5, fibreG: null, unitGrams: 90, unitLabel: "tin (drained)", aliases: ["sardines", "pilchards"] },
  { slug: "sardines-tomato", name: "Sardines, tinned in tomato sauce", category: "fish", kcal: 162, proteinG: 17, carbsG: 1.4, fatG: 9.9, fibreG: null, unitGrams: 120, unitLabel: "tin", aliases: [] },
  { slug: "anchovies-oil", name: "Anchovies, tinned in oil, drained", category: "fish", kcal: 210, proteinG: 29, carbsG: 0, fatG: 10, fibreG: null, unitGrams: 4, unitLabel: "fillet", aliases: ["anchovy"] },
  { slug: "prawns-cooked", name: "Prawns, cooked", category: "fish", kcal: 99, proteinG: 23, carbsG: 0, fatG: 0.8, fibreG: null, unitGrams: 10, unitLabel: "king prawn", aliases: ["shrimp", "prawn", "king prawns", "cooked shrimp"] },
  { slug: "prawns-raw", name: "Prawns, raw", category: "fish", kcal: 71, proteinG: 17, carbsG: 0, fatG: 0.5, fibreG: null, unitGrams: 12, unitLabel: "king prawn", aliases: ["raw shrimp", "raw prawns"] },
  { slug: "mussels-cooked", name: "Mussels, cooked", category: "fish", kcal: 172, proteinG: 24, carbsG: 7.4, fatG: 4.5, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["moules"] },
  { slug: "scallops-cooked", name: "Scallops, cooked", category: "fish", kcal: 111, proteinG: 20.5, carbsG: 5.4, fatG: 0.8, fibreG: null, unitGrams: 20, unitLabel: "scallop", aliases: [] },
  { slug: "crab-meat", name: "Crab meat, cooked", category: "fish", kcal: 97, proteinG: 19, carbsG: 0, fatG: 1.5, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["white crab meat"] },
  { slug: "squid-raw", name: "Squid, raw", category: "fish", kcal: 92, proteinG: 15.6, carbsG: 3, fatG: 1.4, fibreG: null, unitGrams: null, unitLabel: null, aliases: ["calamari"] },

  // ── Eggs ──────────────────────────────────────────────────────────────────
  { slug: "egg-raw", name: "Egg, raw", category: "eggs", kcal: 143, proteinG: 12.6, carbsG: 0.7, fatG: 9.5, fibreG: null, unitGrams: 50, unitLabel: "egg", aliases: ["egg", "eggs", "hen egg", "large egg"] },
  { slug: "egg-boiled", name: "Egg, boiled", category: "eggs", kcal: 155, proteinG: 12.6, carbsG: 1.1, fatG: 10.6, fibreG: null, unitGrams: 50, unitLabel: "egg", aliases: ["boiled egg", "hard boiled egg", "soft boiled egg"] },
  { slug: "egg-poached", name: "Egg, poached", category: "eggs", kcal: 143, proteinG: 12.5, carbsG: 0.7, fatG: 9.5, fibreG: null, unitGrams: 50, unitLabel: "egg", aliases: ["poached egg"] },
  { slug: "egg-fried", name: "Egg, fried", category: "eggs", kcal: 196, proteinG: 13.6, carbsG: 0.8, fatG: 14.8, fibreG: null, unitGrams: 55, unitLabel: "egg", aliases: ["fried egg"] },
  { slug: "egg-scrambled", name: "Egg, scrambled with milk", category: "eggs", kcal: 149, proteinG: 10, carbsG: 1.6, fatG: 11, fibreG: null, unitGrams: 110, unitLabel: "2-egg serving", aliases: ["scrambled eggs", "omelette"] },
  { slug: "egg-white", name: "Egg white", category: "eggs", kcal: 52, proteinG: 11, carbsG: 0.7, fatG: 0.2, fibreG: null, unitGrams: 33, unitLabel: "white", aliases: ["egg whites", "liquid egg white", "egg white carton"] },
  { slug: "egg-yolk", name: "Egg yolk", category: "eggs", kcal: 322, proteinG: 16, carbsG: 3.6, fatG: 27, fibreG: null, unitGrams: 17, unitLabel: "yolk", aliases: ["yolk"] },
  { slug: "duck-egg", name: "Duck egg", category: "eggs", kcal: 185, proteinG: 13, carbsG: 1.4, fatG: 14, fibreG: null, unitGrams: 70, unitLabel: "egg", aliases: [] },

  // ── Dairy ─────────────────────────────────────────────────────────────────
  { slug: "milk-whole", name: "Whole milk", category: "dairy", kcal: 64, proteinG: 3.4, carbsG: 4.7, fatG: 3.6, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["milk", "full fat milk", "whole fat milk"] },
  { slug: "milk-semi-skimmed", name: "Semi-skimmed milk", category: "dairy", kcal: 50, proteinG: 3.6, carbsG: 4.8, fatG: 1.8, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["2% milk", "reduced fat milk", "milk"] },
  { slug: "milk-skimmed", name: "Skimmed milk", category: "dairy", kcal: 35, proteinG: 3.5, carbsG: 5, fatG: 0.2, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["skim milk", "fat free milk", "nonfat milk"] },
  { slug: "oat-milk", name: "Oat milk", category: "dairy", kcal: 46, proteinG: 1, carbsG: 6.7, fatG: 1.5, fibreG: 0.8, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["oat drink", "oatly"] },
  { slug: "almond-milk-unsweetened", name: "Almond milk, unsweetened", category: "dairy", kcal: 13, proteinG: 0.5, carbsG: 0.3, fatG: 1.1, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["almond drink", "unsweetened almond milk"] },
  { slug: "soya-milk-unsweetened", name: "Soya milk, unsweetened", category: "dairy", kcal: 33, proteinG: 3.3, carbsG: 0.6, fatG: 1.8, fibreG: 0.5, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["soy milk", "soya drink"] },
  { slug: "greek-yoghurt-0", name: "Greek yoghurt, 0% fat", category: "dairy", kcal: 57, proteinG: 10, carbsG: 4, fatG: 0.2, fibreG: null, unitGrams: 170, unitLabel: "pot", aliases: ["greek yogurt", "fat free greek yoghurt", "0% greek yoghurt", "greek yoghurt"] },
  { slug: "greek-yoghurt-5", name: "Greek yoghurt, 5% fat", category: "dairy", kcal: 97, proteinG: 9, carbsG: 3, fatG: 5, fibreG: null, unitGrams: 170, unitLabel: "pot", aliases: ["full fat greek yoghurt", "greek yogurt 5%"] },
  { slug: "skyr", name: "Skyr", category: "dairy", kcal: 63, proteinG: 11, carbsG: 4, fatG: 0.2, fibreG: null, unitGrams: 150, unitLabel: "pot", aliases: ["icelandic yoghurt", "icelandic style yogurt"] },
  { slug: "high-protein-yoghurt", name: "High-protein yoghurt", category: "dairy", kcal: 68, proteinG: 10, carbsG: 6, fatG: 0.2, fibreG: null, unitGrams: 200, unitLabel: "pot", aliases: ["protein yoghurt", "protein yogurt", "arla protein"] },
  { slug: "natural-yoghurt", name: "Natural yoghurt, whole milk", category: "dairy", kcal: 61, proteinG: 3.5, carbsG: 4.7, fatG: 3.3, fibreG: null, unitGrams: 150, unitLabel: "pot", aliases: ["plain yoghurt", "plain yogurt", "natural yogurt"] },
  { slug: "fruit-yoghurt-low-fat", name: "Fruit yoghurt, low fat", category: "dairy", kcal: 92, proteinG: 4, carbsG: 14, fatG: 2, fibreG: null, unitGrams: 125, unitLabel: "pot", aliases: ["flavoured yoghurt", "strawberry yoghurt"] },
  { slug: "quark", name: "Quark", category: "dairy", kcal: 71, proteinG: 12.5, carbsG: 4, fatG: 0.2, fibreG: null, unitGrams: 250, unitLabel: "tub", aliases: ["fat free quark"] },
  { slug: "cottage-cheese", name: "Cottage cheese", category: "dairy", kcal: 98, proteinG: 12, carbsG: 3.5, fatG: 4.3, fibreG: null, unitGrams: 150, unitLabel: "portion", aliases: ["curd cheese"] },
  { slug: "cottage-cheese-low-fat", name: "Cottage cheese, low fat", category: "dairy", kcal: 72, proteinG: 12.6, carbsG: 3.3, fatG: 1.5, fibreG: null, unitGrams: 150, unitLabel: "portion", aliases: ["reduced fat cottage cheese"] },
  { slug: "cheddar", name: "Cheddar", category: "dairy", kcal: 416, proteinG: 25, carbsG: 0.1, fatG: 35, fibreG: null, unitGrams: 30, unitLabel: "matchbox portion", aliases: ["cheese", "mature cheddar", "grated cheese"] },
  { slug: "cheddar-reduced-fat", name: "Cheddar, reduced fat", category: "dairy", kcal: 273, proteinG: 32, carbsG: 0.1, fatG: 16, fibreG: null, unitGrams: 30, unitLabel: "matchbox portion", aliases: ["light cheddar", "half fat cheddar"] },
  { slug: "mozzarella", name: "Mozzarella", category: "dairy", kcal: 300, proteinG: 22, carbsG: 2.2, fatG: 22, fibreG: null, unitGrams: 125, unitLabel: "ball", aliases: ["buffalo mozzarella"] },
  { slug: "mozzarella-light", name: "Mozzarella, light", category: "dairy", kcal: 224, proteinG: 27, carbsG: 1.5, fatG: 12.5, fibreG: null, unitGrams: 125, unitLabel: "ball", aliases: ["reduced fat mozzarella", "light mozzarella"] },
  { slug: "feta", name: "Feta", category: "dairy", kcal: 264, proteinG: 14.2, carbsG: 4.1, fatG: 21.3, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["greek cheese", "salad cheese"] },
  { slug: "parmesan", name: "Parmesan", category: "dairy", kcal: 392, proteinG: 36, carbsG: 3.2, fatG: 26, fibreG: null, unitGrams: 10, unitLabel: "tbsp grated", aliases: ["parmigiano", "grana padano", "pecorino"] },
  { slug: "halloumi", name: "Halloumi", category: "dairy", kcal: 321, proteinG: 22, carbsG: 2, fatG: 25, fibreG: null, unitGrams: 60, unitLabel: "portion", aliases: ["grilling cheese"] },
  { slug: "paneer", name: "Paneer", category: "dairy", kcal: 296, proteinG: 19, carbsG: 1.5, fatG: 23, fibreG: null, unitGrams: 120, unitLabel: "portion", aliases: ["indian cheese"] },
  { slug: "brie", name: "Brie", category: "dairy", kcal: 334, proteinG: 21, carbsG: 0.5, fatG: 28, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["camembert"] },
  { slug: "goats-cheese", name: "Goat's cheese, soft", category: "dairy", kcal: 268, proteinG: 18, carbsG: 2.5, fatG: 21, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["chevre", "goat cheese"] },
  { slug: "ricotta", name: "Ricotta", category: "dairy", kcal: 174, proteinG: 11, carbsG: 3, fatG: 13, fibreG: null, unitGrams: 60, unitLabel: "portion", aliases: [] },
  { slug: "cream-cheese", name: "Cream cheese, full fat", category: "dairy", kcal: 342, proteinG: 6, carbsG: 4, fatG: 34, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["philadelphia", "soft cheese"] },
  { slug: "cream-cheese-light", name: "Cream cheese, light", category: "dairy", kcal: 175, proteinG: 7.5, carbsG: 5, fatG: 13, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["light soft cheese", "reduced fat cream cheese"] },
  { slug: "cream-single", name: "Single cream", category: "dairy", kcal: 198, proteinG: 2.6, carbsG: 4, fatG: 19, fibreG: null, unitGrams: 30, unitLabel: "tbsp", aliases: ["light cream", "pouring cream"] },
  { slug: "cream-double", name: "Double cream", category: "dairy", kcal: 449, proteinG: 1.7, carbsG: 2.7, fatG: 48, fibreG: null, unitGrams: 30, unitLabel: "tbsp", aliases: ["heavy cream", "whipping cream"] },
  { slug: "soured-cream", name: "Soured cream", category: "dairy", kcal: 198, proteinG: 2.4, carbsG: 4.6, fatG: 19.4, fibreG: null, unitGrams: 30, unitLabel: "tbsp", aliases: ["sour cream"] },
  { slug: "creme-fraiche", name: "Crème fraîche, full fat", category: "dairy", kcal: 292, proteinG: 2.4, carbsG: 3, fatG: 30, fibreG: null, unitGrams: 30, unitLabel: "tbsp", aliases: ["creme fraiche"] },
  { slug: "ice-cream-vanilla", name: "Vanilla ice cream", category: "dairy", kcal: 207, proteinG: 3.5, carbsG: 24, fatG: 11, fibreG: null, unitGrams: 65, unitLabel: "scoop", aliases: ["ice cream"] },

  // ── Bread, grains, cereals and pasta ──────────────────────────────────────
  { slug: "bread-wholemeal", name: "Wholemeal bread", category: "grain", kcal: 227, proteinG: 10.5, carbsG: 38, fatG: 2.5, fibreG: 6.5, unitGrams: 40, unitLabel: "slice", aliases: ["bread", "brown bread", "whole wheat bread", "wholegrain bread"] },
  { slug: "bread-white", name: "White bread", category: "grain", kcal: 265, proteinG: 9, carbsG: 49, fatG: 3.2, fibreG: 2.7, unitGrams: 36, unitLabel: "slice", aliases: ["white sliced bread", "toast"] },
  { slug: "bread-sourdough", name: "Sourdough bread", category: "grain", kcal: 270, proteinG: 9.5, carbsG: 51, fatG: 1.5, fibreG: 2.4, unitGrams: 50, unitLabel: "slice", aliases: ["sourdough"] },
  { slug: "bread-rye", name: "Rye bread", category: "grain", kcal: 259, proteinG: 8.5, carbsG: 48, fatG: 3.3, fibreG: 5.8, unitGrams: 32, unitLabel: "slice", aliases: ["pumpernickel", "dark rye"] },
  { slug: "bagel", name: "Bagel, plain", category: "grain", kcal: 250, proteinG: 10, carbsG: 49, fatG: 1.5, fibreG: 2, unitGrams: 85, unitLabel: "bagel", aliases: ["bagel thin", "plain bagel"] },
  { slug: "pitta-wholemeal", name: "Wholemeal pitta bread", category: "grain", kcal: 265, proteinG: 9.5, carbsG: 50, fatG: 1.5, fibreG: 6.5, unitGrams: 60, unitLabel: "pitta", aliases: ["pitta", "pita bread", "wholemeal pita"] },
  { slug: "bread-roll", name: "Bread roll, crusty", category: "grain", kcal: 280, proteinG: 9.5, carbsG: 53, fatG: 2.5, fibreG: 2.5, unitGrams: 60, unitLabel: "roll", aliases: ["crusty roll", "baguette", "bap", "sub roll"] },
  { slug: "burger-bun-wholemeal", name: "Wholemeal burger bun", category: "grain", kcal: 270, proteinG: 9, carbsG: 48, fatG: 4, fibreG: 4, unitGrams: 60, unitLabel: "bun", aliases: ["burger bun", "wholemeal bun", "brioche bun"] },
  { slug: "tortilla-wrap-white", name: "Tortilla wrap, white", category: "grain", kcal: 300, proteinG: 8, carbsG: 50, fatG: 7, fibreG: 3, unitGrams: 62, unitLabel: "large wrap", aliases: ["wrap", "tortilla", "flour tortilla", "large tortilla wrap"] },
  { slug: "tortilla-wrap-wholemeal", name: "Tortilla wrap, wholemeal", category: "grain", kcal: 290, proteinG: 10, carbsG: 44, fatG: 7, fibreG: 7, unitGrams: 64, unitLabel: "large wrap", aliases: ["wholemeal wrap", "whole wheat tortilla"] },
  { slug: "tortilla-corn", name: "Corn tortilla", category: "grain", kcal: 218, proteinG: 5.7, carbsG: 40, fatG: 2.8, fibreG: 5, unitGrams: 26, unitLabel: "small tortilla", aliases: ["small tortilla", "soft taco"] },
  { slug: "naan", name: "Naan bread", category: "grain", kcal: 300, proteinG: 8.5, carbsG: 50, fatG: 7.5, fibreG: 2.5, unitGrams: 90, unitLabel: "naan", aliases: ["nan bread"] },
  { slug: "crumpet", name: "Crumpet", category: "grain", kcal: 180, proteinG: 6, carbsG: 36, fatG: 0.9, fibreG: 2, unitGrams: 55, unitLabel: "crumpet", aliases: [] },
  { slug: "english-muffin", name: "English muffin", category: "grain", kcal: 235, proteinG: 8, carbsG: 46, fatG: 1.8, fibreG: 2.5, unitGrams: 60, unitLabel: "muffin", aliases: ["breakfast muffin", "toasting muffin"] },
  { slug: "croissant", name: "Croissant", category: "grain", kcal: 406, proteinG: 8, carbsG: 46, fatG: 21, fibreG: 2.6, unitGrams: 60, unitLabel: "croissant", aliases: [] },
  { slug: "oats-dry", name: "Porridge oats, dry", category: "grain", kcal: 372, proteinG: 11, carbsG: 60, fatG: 8, fibreG: 9, unitGrams: 40, unitLabel: "serving", aliases: ["oats", "rolled oats", "oatmeal", "jumbo oats"] },
  { slug: "porridge-water", name: "Porridge, made with water", category: "grain", kcal: 71, proteinG: 2.5, carbsG: 12, fatG: 1.5, fibreG: 1.7, unitGrams: 250, unitLabel: "bowl", aliases: ["oatmeal cooked", "porridge"] },
  { slug: "granola", name: "Granola", category: "grain", kcal: 450, proteinG: 9, carbsG: 60, fatG: 18, fibreG: 6, unitGrams: 45, unitLabel: "serving", aliases: ["crunchy oat cereal"] },
  { slug: "muesli", name: "Muesli", category: "grain", kcal: 360, proteinG: 10, carbsG: 60, fatG: 8, fibreG: 7, unitGrams: 45, unitLabel: "serving", aliases: ["swiss muesli"] },
  { slug: "weetabix", name: "Wheat biscuit cereal", category: "grain", kcal: 362, proteinG: 12, carbsG: 69, fatG: 2, fibreG: 10, unitGrams: 19, unitLabel: "biscuit", aliases: ["weetabix", "wheat bisks"] },
  { slug: "cornflakes", name: "Cornflakes", category: "grain", kcal: 378, proteinG: 7, carbsG: 84, fatG: 0.9, fibreG: 3, unitGrams: 30, unitLabel: "bowl", aliases: ["corn flakes"] },
  { slug: "bran-flakes", name: "Bran flakes", category: "grain", kcal: 356, proteinG: 10, carbsG: 66, fatG: 2, fibreG: 15, unitGrams: 40, unitLabel: "bowl", aliases: ["all bran flakes"] },
  { slug: "rice-white-cooked", name: "White rice, cooked", category: "grain", kcal: 130, proteinG: 2.7, carbsG: 28, fatG: 0.3, fibreG: 0.4, unitGrams: 180, unitLabel: "portion", aliases: ["rice", "boiled rice", "basmati rice", "jasmine rice", "long grain rice"] },
  { slug: "rice-brown-cooked", name: "Brown rice, cooked", category: "grain", kcal: 123, proteinG: 2.7, carbsG: 25.6, fatG: 1, fibreG: 1.6, unitGrams: 180, unitLabel: "portion", aliases: ["wholegrain rice"] },
  { slug: "rice-pouch", name: "Microwave rice pouch", category: "grain", kcal: 154, proteinG: 3.2, carbsG: 30, fatG: 2, fibreG: 1.5, unitGrams: 250, unitLabel: "pouch", aliases: ["pouch rice", "microwave rice", "ready rice", "basmati pouch"] },
  { slug: "pasta-dried", name: "Pasta, dried", category: "grain", kcal: 371, proteinG: 13, carbsG: 75, fatG: 1.5, fibreG: 3, unitGrams: 75, unitLabel: "portion", aliases: ["dried pasta", "spaghetti", "penne", "fusilli", "linguine", "orzo", "macaroni"] },
  { slug: "pasta-cooked", name: "Pasta, cooked", category: "grain", kcal: 158, proteinG: 5.8, carbsG: 31, fatG: 0.9, fibreG: 1.8, unitGrams: 180, unitLabel: "portion", aliases: ["cooked pasta", "boiled spaghetti", "cooked spaghetti"] },
  { slug: "pasta-wholewheat-dried", name: "Wholewheat pasta, dried", category: "grain", kcal: 348, proteinG: 13.5, carbsG: 65, fatG: 2.5, fibreG: 9, unitGrams: 75, unitLabel: "portion", aliases: ["wholemeal pasta", "wholewheat spaghetti"] },
  { slug: "pasta-wholewheat-cooked", name: "Wholewheat pasta, cooked", category: "grain", kcal: 149, proteinG: 6, carbsG: 30, fatG: 1.3, fibreG: 4, unitGrams: 180, unitLabel: "portion", aliases: ["wholemeal pasta cooked"] },
  { slug: "fresh-filled-pasta", name: "Fresh filled pasta", category: "grain", kcal: 265, proteinG: 10, carbsG: 40, fatG: 7, fibreG: 2.5, unitGrams: 250, unitLabel: "pack", aliases: ["tortelloni", "tortellini", "ravioli", "spinach and ricotta tortelloni"] },
  { slug: "gnocchi", name: "Gnocchi", category: "grain", kcal: 160, proteinG: 4, carbsG: 33, fatG: 0.5, fibreG: 2, unitGrams: 250, unitLabel: "pack", aliases: ["potato gnocchi"] },
  { slug: "egg-noodles-dried", name: "Egg noodles, dried", category: "grain", kcal: 362, proteinG: 12, carbsG: 71, fatG: 3, fibreG: 3, unitGrams: 62, unitLabel: "nest", aliases: ["noodles", "medium egg noodles"] },
  { slug: "egg-noodles-cooked", name: "Egg noodles, cooked", category: "grain", kcal: 138, proteinG: 4.5, carbsG: 25, fatG: 2, fibreG: 1.2, unitGrams: 150, unitLabel: "portion", aliases: ["cooked noodles"] },
  { slug: "rice-noodles-dried", name: "Rice noodles, dried", category: "grain", kcal: 364, proteinG: 6, carbsG: 83, fatG: 0.6, fibreG: 1.6, unitGrams: 60, unitLabel: "nest", aliases: ["vermicelli noodles", "flat rice noodles"] },
  { slug: "rice-noodles-cooked", name: "Rice noodles, cooked", category: "grain", kcal: 109, proteinG: 0.9, carbsG: 25, fatG: 0.2, fibreG: 1, unitGrams: 150, unitLabel: "portion", aliases: ["cooked rice noodles"] },
  { slug: "couscous-dry", name: "Couscous, dry", category: "grain", kcal: 376, proteinG: 13, carbsG: 77, fatG: 0.6, fibreG: 5, unitGrams: 60, unitLabel: "portion", aliases: ["dry couscous"] },
  { slug: "couscous-cooked", name: "Couscous, cooked", category: "grain", kcal: 112, proteinG: 3.8, carbsG: 23, fatG: 0.2, fibreG: 1.4, unitGrams: 180, unitLabel: "portion", aliases: ["cooked couscous"] },
  { slug: "quinoa-dry", name: "Quinoa, dry", category: "grain", kcal: 368, proteinG: 14, carbsG: 64, fatG: 6, fibreG: 7, unitGrams: 60, unitLabel: "portion", aliases: ["dry quinoa"] },
  { slug: "quinoa-cooked", name: "Quinoa, cooked", category: "grain", kcal: 120, proteinG: 4.4, carbsG: 21, fatG: 1.9, fibreG: 2.8, unitGrams: 180, unitLabel: "portion", aliases: ["cooked quinoa"] },
  { slug: "bulgur-cooked", name: "Bulgur wheat, cooked", category: "grain", kcal: 78, proteinG: 3, carbsG: 15, fatG: 0.2, fibreG: 4.5, unitGrams: 180, unitLabel: "portion", aliases: ["bulghur", "cracked wheat"] },
  { slug: "pearl-barley-cooked", name: "Pearl barley, cooked", category: "grain", kcal: 123, proteinG: 2.3, carbsG: 28, fatG: 0.4, fibreG: 3.8, unitGrams: 180, unitLabel: "portion", aliases: ["barley"] },
  { slug: "rye-crispbread", name: "Rye crispbread", category: "grain", kcal: 334, proteinG: 9, carbsG: 63, fatG: 1.7, fibreG: 16, unitGrams: 10, unitLabel: "crispbread", aliases: ["ryvita", "rye cracker", "rye crackers", "crispbread"] },
  { slug: "oatcake", name: "Oatcake", category: "grain", kcal: 440, proteinG: 10, carbsG: 60, fatG: 18, fibreG: 6, unitGrams: 13, unitLabel: "oatcake", aliases: ["oat cakes"] },
  { slug: "croutons", name: "Croutons", category: "grain", kcal: 407, proteinG: 11, carbsG: 74, fatG: 6.6, fibreG: 5, unitGrams: 15, unitLabel: "small handful", aliases: [] },
  { slug: "flour-plain", name: "Plain flour", category: "grain", kcal: 341, proteinG: 9.4, carbsG: 71, fatG: 1.3, fibreG: 3, unitGrams: 15, unitLabel: "tbsp", aliases: ["all purpose flour", "white flour"] },
  { slug: "flour-wholemeal", name: "Wholemeal flour", category: "grain", kcal: 324, proteinG: 12.7, carbsG: 64, fatG: 2.2, fibreG: 9, unitGrams: 15, unitLabel: "tbsp", aliases: ["whole wheat flour"] },
  { slug: "cornflour", name: "Cornflour", category: "grain", kcal: 381, proteinG: 0.3, carbsG: 91, fatG: 0.1, fibreG: 0.9, unitGrams: 8, unitLabel: "tbsp", aliases: ["cornstarch"] },
  { slug: "breadcrumbs", name: "Breadcrumbs, dried", category: "grain", kcal: 395, proteinG: 13, carbsG: 72, fatG: 5, fibreG: 4.5, unitGrams: 15, unitLabel: "tbsp", aliases: ["panko"] },

  // ── Legumes, pulses and soya ──────────────────────────────────────────────
  { slug: "chickpeas-tinned", name: "Chickpeas, tinned, drained", category: "legume", kcal: 139, proteinG: 7.1, carbsG: 22, fatG: 2.6, fibreG: 6.4, unitGrams: 240, unitLabel: "tin (drained)", aliases: ["chickpeas", "garbanzo beans", "garbanzo", "chana"] },
  { slug: "kidney-beans-tinned", name: "Kidney beans, tinned, drained", category: "legume", kcal: 120, proteinG: 8.5, carbsG: 21, fatG: 0.5, fibreG: 6.5, unitGrams: 235, unitLabel: "tin (drained)", aliases: ["kidney beans", "red kidney beans", "rajma"] },
  { slug: "black-beans-tinned", name: "Black beans, tinned, drained", category: "legume", kcal: 114, proteinG: 7.6, carbsG: 20, fatG: 0.5, fibreG: 8, unitGrams: 235, unitLabel: "tin (drained)", aliases: ["black beans", "black turtle beans", "tinned black beans"] },
  { slug: "butter-beans-tinned", name: "Butter beans, tinned, drained", category: "legume", kcal: 103, proteinG: 7, carbsG: 15, fatG: 0.6, fibreG: 5, unitGrams: 235, unitLabel: "tin (drained)", aliases: ["butter beans", "lima beans"] },
  { slug: "cannellini-beans-tinned", name: "Cannellini beans, tinned, drained", category: "legume", kcal: 108, proteinG: 7, carbsG: 17, fatG: 0.5, fibreG: 5.5, unitGrams: 235, unitLabel: "tin (drained)", aliases: ["white beans", "haricot beans", "navy beans"] },
  { slug: "baked-beans", name: "Baked beans in tomato sauce", category: "legume", kcal: 78, proteinG: 4.8, carbsG: 12.5, fatG: 0.4, fibreG: 3.7, unitGrams: 200, unitLabel: "half tin", aliases: ["baked beans", "beans on toast"] },
  { slug: "refried-beans", name: "Refried beans", category: "legume", kcal: 90, proteinG: 5, carbsG: 15, fatG: 1, fibreG: 5, unitGrams: 200, unitLabel: "half tin", aliases: [] },
  { slug: "lentils-green-cooked", name: "Green lentils, cooked", category: "legume", kcal: 116, proteinG: 9, carbsG: 20, fatG: 0.4, fibreG: 8, unitGrams: 150, unitLabel: "portion", aliases: ["lentils", "puy lentils", "brown lentils", "cooked green lentils"] },
  { slug: "lentils-red-dry", name: "Red lentils, dry", category: "legume", kcal: 318, proteinG: 23.8, carbsG: 48, fatG: 1.3, fibreG: 11, unitGrams: 100, unitLabel: "portion", aliases: ["red lentils", "split red lentils", "masoor dal"] },
  { slug: "lentils-red-cooked", name: "Red lentils, cooked", category: "legume", kcal: 110, proteinG: 8, carbsG: 18, fatG: 0.4, fibreG: 4, unitGrams: 180, unitLabel: "portion", aliases: ["dal", "cooked red lentils"] },
  { slug: "lentils-pouch", name: "Cooked lentil pouch", category: "legume", kcal: 130, proteinG: 8.5, carbsG: 17, fatG: 2, fibreG: 5, unitGrams: 250, unitLabel: "pouch", aliases: ["puy lentil pouch", "ready to eat lentils", "pouch lentils"] },
  { slug: "split-peas-cooked", name: "Split peas, cooked", category: "legume", kcal: 118, proteinG: 8.3, carbsG: 21, fatG: 0.4, fibreG: 8, unitGrams: 180, unitLabel: "portion", aliases: ["yellow split peas"] },
  { slug: "edamame", name: "Edamame beans, cooked", category: "legume", kcal: 121, proteinG: 12, carbsG: 8.9, fatG: 5.2, fibreG: 5, unitGrams: 100, unitLabel: "portion", aliases: ["edamame", "soya beans", "soy beans"] },
  { slug: "tofu-firm", name: "Tofu, firm", category: "legume", kcal: 120, proteinG: 13, carbsG: 1, fatG: 7, fibreG: 1, unitGrams: 120, unitLabel: "portion", aliases: ["tofu", "bean curd", "firm tofu"] },
  { slug: "tofu-silken", name: "Tofu, silken", category: "legume", kcal: 55, proteinG: 4.8, carbsG: 2, fatG: 2.7, fibreG: null, unitGrams: 120, unitLabel: "portion", aliases: ["soft tofu", "silken tofu"] },
  { slug: "tempeh", name: "Tempeh", category: "legume", kcal: 192, proteinG: 20.3, carbsG: 7.6, fatG: 10.8, fibreG: null, unitGrams: 100, unitLabel: "portion", aliases: [] },
  { slug: "soya-mince", name: "Soya mince, cooked", category: "legume", kcal: 110, proteinG: 14, carbsG: 5, fatG: 3, fibreG: 4, unitGrams: 100, unitLabel: "portion", aliases: ["soya mince", "soy mince", "vegetarian mince", "meat free mince"] },
  { slug: "quorn-mince", name: "Quorn mince", category: "legume", kcal: 100, proteinG: 14.5, carbsG: 4, fatG: 2, fibreG: 6, unitGrams: 100, unitLabel: "portion", aliases: ["mycoprotein", "quorn"] },
  { slug: "quorn-pieces", name: "Quorn pieces", category: "legume", kcal: 96, proteinG: 15, carbsG: 3, fatG: 2, fibreG: 6, unitGrams: 100, unitLabel: "portion", aliases: ["quorn chicken pieces", "meat free chicken pieces"] },
  { slug: "hummus", name: "Hummus", category: "legume", kcal: 300, proteinG: 7.5, carbsG: 11, fatG: 25, fibreG: 4, unitGrams: 50, unitLabel: "portion", aliases: ["houmous", "hommus", "chickpea dip"] },
  { slug: "falafel", name: "Falafel", category: "legume", kcal: 333, proteinG: 13.3, carbsG: 31.8, fatG: 17.8, fibreG: 5, unitGrams: 20, unitLabel: "falafel", aliases: [] },

  // ── Vegetables ────────────────────────────────────────────────────────────
  { slug: "broccoli", name: "Broccoli, boiled", category: "vegetable", kcal: 35, proteinG: 3, carbsG: 4, fatG: 0.4, fibreG: 3, unitGrams: 80, unitLabel: "portion", aliases: ["broccoli", "tenderstem broccoli", "calabrese"] },
  { slug: "cauliflower", name: "Cauliflower, boiled", category: "vegetable", kcal: 25, proteinG: 2, carbsG: 3, fatG: 0.5, fibreG: 2, unitGrams: 80, unitLabel: "portion", aliases: ["cauli"] },
  { slug: "carrot", name: "Carrot, raw", category: "vegetable", kcal: 35, proteinG: 0.6, carbsG: 7.9, fatG: 0.3, fibreG: 2.4, unitGrams: 61, unitLabel: "medium carrot", aliases: ["carrots", "baby carrots"] },
  { slug: "onion", name: "Onion, raw", category: "vegetable", kcal: 38, proteinG: 1.2, carbsG: 7.9, fatG: 0.2, fibreG: 1.7, unitGrams: 110, unitLabel: "medium onion", aliases: ["onions", "red onion", "white onion", "brown onion", "shallot"] },
  { slug: "spring-onion", name: "Spring onion", category: "vegetable", kcal: 30, proteinG: 1.8, carbsG: 5, fatG: 0.2, fibreG: 2.5, unitGrams: 15, unitLabel: "spring onion", aliases: ["scallion", "green onion", "salad onion"] },
  { slug: "garlic", name: "Garlic", category: "vegetable", kcal: 149, proteinG: 6.4, carbsG: 30, fatG: 0.5, fibreG: 2.1, unitGrams: 3, unitLabel: "clove", aliases: ["garlic cloves"] },
  { slug: "ginger", name: "Ginger, fresh", category: "vegetable", kcal: 80, proteinG: 1.8, carbsG: 16, fatG: 0.8, fibreG: 2, unitGrams: 5, unitLabel: "tsp grated", aliases: ["root ginger", "fresh ginger"] },
  { slug: "tomato", name: "Tomato", category: "vegetable", kcal: 18, proteinG: 0.9, carbsG: 3.1, fatG: 0.2, fibreG: 1.2, unitGrams: 123, unitLabel: "medium tomato", aliases: ["tomatoes", "salad tomato", "vine tomato"] },
  { slug: "cherry-tomatoes", name: "Cherry tomatoes", category: "vegetable", kcal: 18, proteinG: 0.9, carbsG: 3.1, fatG: 0.2, fibreG: 1.2, unitGrams: 17, unitLabel: "tomato", aliases: ["baby plum tomatoes", "cherry tomato"] },
  { slug: "chopped-tomatoes-tinned", name: "Chopped tomatoes, tinned", category: "vegetable", kcal: 20, proteinG: 1.2, carbsG: 3, fatG: 0.2, fibreG: 1, unitGrams: 400, unitLabel: "tin", aliases: ["tinned tomatoes", "canned tomatoes", "plum tomatoes"] },
  { slug: "passata", name: "Passata", category: "sauce", kcal: 30, proteinG: 1.5, carbsG: 5, fatG: 0.2, fibreG: 1.5, unitGrams: 500, unitLabel: "carton", aliases: ["sieved tomatoes", "tomato passata"] },
  { slug: "tomato-puree", name: "Tomato purée", category: "sauce", kcal: 82, proteinG: 4.5, carbsG: 15, fatG: 0.5, fibreG: 3, unitGrams: 16, unitLabel: "tbsp", aliases: ["tomato paste"] },
  { slug: "cucumber", name: "Cucumber", category: "vegetable", kcal: 15, proteinG: 0.7, carbsG: 3, fatG: 0.1, fibreG: 0.5, unitGrams: 300, unitLabel: "cucumber", aliases: [] },
  { slug: "lettuce-romaine", name: "Romaine lettuce", category: "vegetable", kcal: 16, proteinG: 1.2, carbsG: 2, fatG: 0.3, fibreG: 1.5, unitGrams: 180, unitLabel: "romaine heart", aliases: ["lettuce", "cos lettuce", "little gem", "iceberg lettuce"] },
  { slug: "salad-leaves", name: "Mixed salad leaves", category: "vegetable", kcal: 20, proteinG: 2, carbsG: 2, fatG: 0.4, fibreG: 1.5, unitGrams: 30, unitLabel: "handful", aliases: ["salad leaves", "mixed leaves", "leafy salad", "spring mix"] },
  { slug: "rocket", name: "Rocket", category: "vegetable", kcal: 25, proteinG: 2.6, carbsG: 2, fatG: 0.7, fibreG: 1.6, unitGrams: 20, unitLabel: "handful", aliases: ["arugula", "roquette"] },
  { slug: "spinach", name: "Spinach", category: "vegetable", kcal: 23, proteinG: 2.9, carbsG: 1.4, fatG: 0.4, fibreG: 2.2, unitGrams: 30, unitLabel: "handful", aliases: ["baby spinach", "fresh spinach", "frozen spinach"] },
  { slug: "kale", name: "Kale", category: "vegetable", kcal: 35, proteinG: 3, carbsG: 4, fatG: 1, fibreG: 3, unitGrams: 50, unitLabel: "handful", aliases: ["curly kale", "cavolo nero"] },
  { slug: "cabbage", name: "Cabbage", category: "vegetable", kcal: 25, proteinG: 1.3, carbsG: 4.7, fatG: 0.1, fibreG: 2.5, unitGrams: 80, unitLabel: "portion", aliases: ["white cabbage", "savoy cabbage", "red cabbage"] },
  { slug: "coleslaw-mix", name: "Coleslaw mix, undressed", category: "vegetable", kcal: 30, proteinG: 1.3, carbsG: 5.3, fatG: 0.2, fibreG: 2, unitGrams: 100, unitLabel: "portion", aliases: ["shredded cabbage and carrot", "slaw mix"] },
  { slug: "brussels-sprouts", name: "Brussels sprouts, boiled", category: "vegetable", kcal: 35, proteinG: 2.9, carbsG: 3.5, fatG: 1.3, fibreG: 3.1, unitGrams: 80, unitLabel: "portion", aliases: ["sprouts"] },
  { slug: "courgette", name: "Courgette", category: "vegetable", kcal: 17, proteinG: 1.2, carbsG: 2, fatG: 0.3, fibreG: 1, unitGrams: 196, unitLabel: "medium courgette", aliases: ["zucchini"] },
  { slug: "aubergine", name: "Aubergine", category: "vegetable", kcal: 25, proteinG: 1, carbsG: 4.5, fatG: 0.2, fibreG: 3, unitGrams: 250, unitLabel: "aubergine", aliases: ["eggplant", "brinjal"] },
  { slug: "pepper-red", name: "Red pepper", category: "vegetable", kcal: 31, proteinG: 1, carbsG: 6, fatG: 0.3, fibreG: 2, unitGrams: 120, unitLabel: "pepper", aliases: ["bell pepper", "capsicum", "peppers", "sweet pepper", "romano pepper"] },
  { slug: "pepper-green", name: "Green pepper", category: "vegetable", kcal: 20, proteinG: 0.9, carbsG: 3.5, fatG: 0.2, fibreG: 1.7, unitGrams: 120, unitLabel: "pepper", aliases: ["green bell pepper", "green capsicum"] },
  { slug: "roasted-peppers-jar", name: "Roasted peppers, jarred", category: "vegetable", kcal: 40, proteinG: 1, carbsG: 5, fatG: 1.5, fibreG: 1.5, unitGrams: 50, unitLabel: "portion", aliases: ["piquillo peppers", "roasted red peppers"] },
  { slug: "chilli-fresh", name: "Chilli, fresh", category: "vegetable", kcal: 40, proteinG: 1.9, carbsG: 7, fatG: 0.4, fibreG: 1.5, unitGrams: 15, unitLabel: "chilli", aliases: ["chili", "red chilli", "chile pepper", "jalapeno"] },
  { slug: "mushrooms", name: "Mushrooms", category: "vegetable", kcal: 22, proteinG: 3.1, carbsG: 1.5, fatG: 0.3, fibreG: 1, unitGrams: 80, unitLabel: "portion", aliases: ["button mushrooms", "chestnut mushrooms", "white mushrooms"] },
  { slug: "green-beans", name: "Green beans, boiled", category: "vegetable", kcal: 31, proteinG: 1.9, carbsG: 5.2, fatG: 0.2, fibreG: 2.7, unitGrams: 80, unitLabel: "portion", aliases: ["french beans", "string beans", "fine beans"] },
  { slug: "asparagus", name: "Asparagus, cooked", category: "vegetable", kcal: 22, proteinG: 2.2, carbsG: 2.5, fatG: 0.2, fibreG: 2, unitGrams: 125, unitLabel: "portion", aliases: ["asparagus spears"] },
  { slug: "sugar-snap-peas", name: "Sugar snap peas", category: "vegetable", kcal: 42, proteinG: 2.8, carbsG: 6.5, fatG: 0.2, fibreG: 2.6, unitGrams: 80, unitLabel: "portion", aliases: ["mangetout", "snow peas", "snap peas"] },
  { slug: "peas-frozen", name: "Garden peas, frozen, boiled", category: "vegetable", kcal: 69, proteinG: 6, carbsG: 9.7, fatG: 0.9, fibreG: 5, unitGrams: 80, unitLabel: "portion", aliases: ["peas", "frozen peas", "petit pois"] },
  { slug: "sweetcorn-tinned", name: "Sweetcorn, tinned", category: "vegetable", kcal: 85, proteinG: 2.9, carbsG: 16, fatG: 1.2, fibreG: 2.5, unitGrams: 80, unitLabel: "portion", aliases: ["sweetcorn", "corn kernels", "canned corn"] },
  { slug: "corn-on-the-cob", name: "Corn on the cob", category: "vegetable", kcal: 96, proteinG: 3.4, carbsG: 17, fatG: 1.5, fibreG: 2, unitGrams: 90, unitLabel: "cob", aliases: ["corn cob", "sweetcorn cob"] },
  { slug: "mixed-vegetables-frozen", name: "Mixed vegetables, frozen", category: "vegetable", kcal: 55, proteinG: 3, carbsG: 9, fatG: 0.5, fibreG: 3.5, unitGrams: 80, unitLabel: "portion", aliases: ["frozen mixed veg", "mixed veg"] },
  { slug: "stir-fry-vegetables", name: "Stir-fry vegetable mix", category: "vegetable", kcal: 35, proteinG: 2, carbsG: 5, fatG: 0.4, fibreG: 2, unitGrams: 300, unitLabel: "pack", aliases: ["stir fry veg", "stir-fry mix"] },
  { slug: "celery", name: "Celery", category: "vegetable", kcal: 16, proteinG: 0.7, carbsG: 2.5, fatG: 0.2, fibreG: 1.6, unitGrams: 40, unitLabel: "stick", aliases: [] },
  { slug: "leek", name: "Leek", category: "vegetable", kcal: 30, proteinG: 1.5, carbsG: 5, fatG: 0.3, fibreG: 2.2, unitGrams: 90, unitLabel: "leek", aliases: ["leeks"] },
  { slug: "beetroot-cooked", name: "Beetroot, cooked", category: "vegetable", kcal: 44, proteinG: 1.7, carbsG: 8, fatG: 0.2, fibreG: 2, unitGrams: 40, unitLabel: "beetroot", aliases: ["beets", "beet"] },
  { slug: "butternut-squash", name: "Butternut squash, cooked", category: "vegetable", kcal: 45, proteinG: 1, carbsG: 10, fatG: 0.1, fibreG: 2, unitGrams: 150, unitLabel: "portion", aliases: ["squash", "pumpkin"] },
  { slug: "olives", name: "Olives, in brine", category: "vegetable", kcal: 145, proteinG: 1, carbsG: 1, fatG: 15, fibreG: 3, unitGrams: 4, unitLabel: "olive", aliases: ["green olives", "black olives", "kalamata olives"] },
  { slug: "potato-boiled", name: "Potato, boiled", category: "vegetable", kcal: 78, proteinG: 1.7, carbsG: 17.8, fatG: 0.3, fibreG: 1.8, unitGrams: 175, unitLabel: "medium potato", aliases: ["potatoes", "new potatoes", "boiled potatoes", "baby potatoes"] },
  { slug: "potato-baked", name: "Jacket potato, baked", category: "vegetable", kcal: 93, proteinG: 2.5, carbsG: 20, fatG: 0.2, fibreG: 2.2, unitGrams: 180, unitLabel: "medium baking potato", aliases: ["baked potato", "jacket potato", "baking potato"] },
  { slug: "sweet-potato-baked", name: "Sweet potato, baked", category: "vegetable", kcal: 90, proteinG: 2, carbsG: 20, fatG: 0.2, fibreG: 3.3, unitGrams: 130, unitLabel: "medium sweet potato", aliases: ["sweet potato", "kumara", "yam"] },

  // ── Fruit ─────────────────────────────────────────────────────────────────
  { slug: "banana", name: "Banana", category: "fruit", kcal: 89, proteinG: 1.1, carbsG: 21, fatG: 0.3, fibreG: 2.6, unitGrams: 118, unitLabel: "medium banana", aliases: ["bananas"] },
  { slug: "apple", name: "Apple", category: "fruit", kcal: 52, proteinG: 0.3, carbsG: 12, fatG: 0.2, fibreG: 2.4, unitGrams: 182, unitLabel: "medium apple", aliases: ["apples", "gala apple", "braeburn"] },
  { slug: "orange", name: "Orange", category: "fruit", kcal: 47, proteinG: 0.9, carbsG: 10, fatG: 0.1, fibreG: 2.4, unitGrams: 131, unitLabel: "medium orange", aliases: ["oranges"] },
  { slug: "satsuma", name: "Satsuma", category: "fruit", kcal: 47, proteinG: 0.8, carbsG: 11, fatG: 0.2, fibreG: 1.7, unitGrams: 74, unitLabel: "satsuma", aliases: ["clementine", "mandarin", "tangerine", "satsumas"] },
  { slug: "pear", name: "Pear", category: "fruit", kcal: 57, proteinG: 0.4, carbsG: 13, fatG: 0.1, fibreG: 3.1, unitGrams: 178, unitLabel: "medium pear", aliases: ["pears"] },
  { slug: "peach", name: "Peach", category: "fruit", kcal: 39, proteinG: 0.9, carbsG: 8.5, fatG: 0.25, fibreG: 1.5, unitGrams: 150, unitLabel: "medium peach", aliases: ["peaches"] },
  { slug: "nectarine", name: "Nectarine", category: "fruit", kcal: 44, proteinG: 1.1, carbsG: 9.5, fatG: 0.3, fibreG: 1.7, unitGrams: 142, unitLabel: "nectarine", aliases: ["nectarines"] },
  { slug: "plum", name: "Plum", category: "fruit", kcal: 46, proteinG: 0.7, carbsG: 10, fatG: 0.3, fibreG: 1.4, unitGrams: 66, unitLabel: "plum", aliases: ["plums"] },
  { slug: "grapes", name: "Grapes", category: "fruit", kcal: 69, proteinG: 0.7, carbsG: 16, fatG: 0.2, fibreG: 0.9, unitGrams: 5, unitLabel: "grape", aliases: ["red grapes", "green grapes"] },
  { slug: "strawberries", name: "Strawberries", category: "fruit", kcal: 32, proteinG: 0.7, carbsG: 6, fatG: 0.3, fibreG: 2, unitGrams: 12, unitLabel: "strawberry", aliases: ["strawberry"] },
  { slug: "blueberries", name: "Blueberries", category: "fruit", kcal: 57, proteinG: 0.7, carbsG: 12.5, fatG: 0.3, fibreG: 2.4, unitGrams: 80, unitLabel: "handful", aliases: ["blueberry"] },
  { slug: "raspberries", name: "Raspberries", category: "fruit", kcal: 40, proteinG: 1.2, carbsG: 7, fatG: 0.5, fibreG: 5, unitGrams: 80, unitLabel: "handful", aliases: ["raspberry"] },
  { slug: "blackberries", name: "Blackberries", category: "fruit", kcal: 43, proteinG: 1.4, carbsG: 8, fatG: 0.5, fibreG: 5, unitGrams: 80, unitLabel: "handful", aliases: ["brambles"] },
  { slug: "mixed-berries-frozen", name: "Mixed berries, frozen", category: "fruit", kcal: 48, proteinG: 1, carbsG: 9, fatG: 0.4, fibreG: 3.5, unitGrams: 100, unitLabel: "portion", aliases: ["berries", "frozen berries", "summer fruits"] },
  { slug: "cherries", name: "Cherries", category: "fruit", kcal: 63, proteinG: 1, carbsG: 15, fatG: 0.2, fibreG: 2, unitGrams: 8, unitLabel: "cherry", aliases: ["cherry"] },
  { slug: "pineapple", name: "Pineapple", category: "fruit", kcal: 50, proteinG: 0.5, carbsG: 12, fatG: 0.1, fibreG: 1.4, unitGrams: 100, unitLabel: "portion", aliases: [] },
  { slug: "mango", name: "Mango", category: "fruit", kcal: 60, proteinG: 0.8, carbsG: 14, fatG: 0.4, fibreG: 1.6, unitGrams: 200, unitLabel: "mango", aliases: [] },
  { slug: "kiwi", name: "Kiwi fruit", category: "fruit", kcal: 61, proteinG: 1.1, carbsG: 13, fatG: 0.5, fibreG: 3, unitGrams: 75, unitLabel: "kiwi", aliases: ["kiwifruit"] },
  { slug: "watermelon", name: "Watermelon", category: "fruit", kcal: 30, proteinG: 0.6, carbsG: 7.1, fatG: 0.15, fibreG: 0.4, unitGrams: 150, unitLabel: "slice", aliases: [] },
  { slug: "melon", name: "Melon", category: "fruit", kcal: 34, proteinG: 0.8, carbsG: 7.5, fatG: 0.2, fibreG: 0.9, unitGrams: 150, unitLabel: "slice", aliases: ["cantaloupe", "honeydew", "galia melon"] },
  { slug: "grapefruit", name: "Grapefruit", category: "fruit", kcal: 42, proteinG: 0.8, carbsG: 9.5, fatG: 0.15, fibreG: 1.6, unitGrams: 123, unitLabel: "half grapefruit", aliases: [] },
  { slug: "avocado", name: "Avocado", category: "fruit", kcal: 160, proteinG: 2, carbsG: 1.8, fatG: 15, fibreG: 6.7, unitGrams: 75, unitLabel: "half avocado", aliases: ["avocados", "hass avocado"] },
  { slug: "lemon", name: "Lemon", category: "fruit", kcal: 29, proteinG: 1.1, carbsG: 6, fatG: 0.3, fibreG: 2.8, unitGrams: 58, unitLabel: "lemon", aliases: ["lemons"] },
  { slug: "lime", name: "Lime", category: "fruit", kcal: 30, proteinG: 0.7, carbsG: 6.5, fatG: 0.2, fibreG: 2.8, unitGrams: 67, unitLabel: "lime", aliases: ["limes"] },
  { slug: "lemon-juice", name: "Lemon juice", category: "fruit", kcal: 22, proteinG: 0.4, carbsG: 5, fatG: 0.2, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["lime juice", "citrus juice"] },
  { slug: "peaches-tinned-juice", name: "Peaches, tinned in juice", category: "fruit", kcal: 50, proteinG: 0.5, carbsG: 12, fatG: 0.1, fibreG: 1, unitGrams: 120, unitLabel: "portion", aliases: ["tinned peaches", "canned peaches"] },
  { slug: "raisins", name: "Raisins", category: "fruit", kcal: 299, proteinG: 3.1, carbsG: 71, fatG: 0.5, fibreG: 4, unitGrams: 30, unitLabel: "small box", aliases: ["sultanas", "currants", "dried grapes"] },
  { slug: "dates", name: "Medjool dates", category: "fruit", kcal: 277, proteinG: 1.8, carbsG: 67, fatG: 0.15, fibreG: 7, unitGrams: 24, unitLabel: "date", aliases: ["dates"] },
  { slug: "dried-apricots", name: "Dried apricots", category: "fruit", kcal: 241, proteinG: 3.4, carbsG: 55, fatG: 0.5, fibreG: 7, unitGrams: 8, unitLabel: "apricot", aliases: ["apricots"] },

  // ── Nuts, seeds and nut butters ───────────────────────────────────────────
  { slug: "almonds", name: "Almonds", category: "nut", kcal: 579, proteinG: 21, carbsG: 9, fatG: 50, fibreG: 12.5, unitGrams: 30, unitLabel: "handful", aliases: ["almond", "flaked almonds"] },
  { slug: "walnuts", name: "Walnuts", category: "nut", kcal: 654, proteinG: 15, carbsG: 7, fatG: 65, fibreG: 6.7, unitGrams: 30, unitLabel: "handful", aliases: ["walnut halves"] },
  { slug: "pecans", name: "Pecans", category: "nut", kcal: 691, proteinG: 9, carbsG: 4, fatG: 72, fibreG: 9.6, unitGrams: 30, unitLabel: "handful", aliases: ["pecan nuts"] },
  { slug: "cashews", name: "Cashews", category: "nut", kcal: 553, proteinG: 18, carbsG: 27, fatG: 44, fibreG: 3.3, unitGrams: 30, unitLabel: "handful", aliases: ["cashew nuts"] },
  { slug: "peanuts", name: "Peanuts", category: "nut", kcal: 567, proteinG: 26, carbsG: 7, fatG: 49, fibreG: 8.5, unitGrams: 30, unitLabel: "handful", aliases: ["salted peanuts", "groundnuts"] },
  { slug: "pistachios", name: "Pistachios", category: "nut", kcal: 560, proteinG: 20, carbsG: 18, fatG: 45, fibreG: 10, unitGrams: 30, unitLabel: "handful", aliases: ["pistachio nuts"] },
  { slug: "hazelnuts", name: "Hazelnuts", category: "nut", kcal: 628, proteinG: 15, carbsG: 7, fatG: 61, fibreG: 9.7, unitGrams: 30, unitLabel: "handful", aliases: ["filberts"] },
  { slug: "brazil-nuts", name: "Brazil nuts", category: "nut", kcal: 659, proteinG: 14, carbsG: 4, fatG: 67, fibreG: 7.5, unitGrams: 5, unitLabel: "nut", aliases: [] },
  { slug: "macadamia-nuts", name: "Macadamia nuts", category: "nut", kcal: 718, proteinG: 8, carbsG: 5, fatG: 76, fibreG: 8.6, unitGrams: 30, unitLabel: "handful", aliases: [] },
  { slug: "pine-nuts", name: "Pine nuts", category: "nut", kcal: 673, proteinG: 14, carbsG: 13, fatG: 68, fibreG: 3.7, unitGrams: 15, unitLabel: "tbsp", aliases: ["pignoli"] },
  { slug: "mixed-nuts", name: "Mixed nuts", category: "nut", kcal: 607, proteinG: 20, carbsG: 12, fatG: 54, fibreG: 7, unitGrams: 30, unitLabel: "handful", aliases: ["nuts", "salted mixed nuts"] },
  { slug: "coconut-desiccated", name: "Desiccated coconut", category: "nut", kcal: 660, proteinG: 6.9, carbsG: 7, fatG: 65, fibreG: 16, unitGrams: 10, unitLabel: "tbsp", aliases: ["shredded coconut"] },
  { slug: "peanut-butter", name: "Peanut butter", category: "nut", kcal: 588, proteinG: 25, carbsG: 12, fatG: 50, fibreG: 6, unitGrams: 16, unitLabel: "tbsp", aliases: ["pb", "crunchy peanut butter", "smooth peanut butter"] },
  { slug: "almond-butter", name: "Almond butter", category: "nut", kcal: 614, proteinG: 21, carbsG: 11, fatG: 56, fibreG: 10, unitGrams: 16, unitLabel: "tbsp", aliases: [] },
  { slug: "tahini", name: "Tahini", category: "nut", kcal: 595, proteinG: 17, carbsG: 10, fatG: 53, fibreG: 9, unitGrams: 15, unitLabel: "tbsp", aliases: ["sesame paste"] },
  { slug: "chia-seeds", name: "Chia seeds", category: "nut", kcal: 486, proteinG: 17, carbsG: 42, fatG: 31, fibreG: 34, unitGrams: 12, unitLabel: "tbsp", aliases: ["chia"] },
  { slug: "flaxseed", name: "Flaxseed", category: "nut", kcal: 534, proteinG: 18, carbsG: 29, fatG: 42, fibreG: 27, unitGrams: 10, unitLabel: "tbsp", aliases: ["linseed", "ground flaxseed"] },
  { slug: "pumpkin-seeds", name: "Pumpkin seeds", category: "nut", kcal: 559, proteinG: 30, carbsG: 11, fatG: 49, fibreG: 6, unitGrams: 15, unitLabel: "tbsp", aliases: ["pepitas"] },
  { slug: "sunflower-seeds", name: "Sunflower seeds", category: "nut", kcal: 584, proteinG: 21, carbsG: 20, fatG: 51, fibreG: 8.6, unitGrams: 15, unitLabel: "tbsp", aliases: [] },
  { slug: "sesame-seeds", name: "Sesame seeds", category: "nut", kcal: 573, proteinG: 17, carbsG: 23, fatG: 50, fibreG: 12, unitGrams: 9, unitLabel: "tbsp", aliases: [] },
  { slug: "mixed-seeds", name: "Mixed seeds", category: "nut", kcal: 570, proteinG: 22, carbsG: 15, fatG: 48, fibreG: 9, unitGrams: 15, unitLabel: "tbsp", aliases: ["seeds", "seed mix"] },

  // ── Oils, butters and spreads ─────────────────────────────────────────────
  { slug: "olive-oil", name: "Olive oil", category: "fat", kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: ["extra virgin olive oil", "evoo", "oil"] },
  { slug: "rapeseed-oil", name: "Rapeseed oil", category: "fat", kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: ["canola oil", "vegetable oil"] },
  { slug: "sunflower-oil", name: "Sunflower oil", category: "fat", kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: [] },
  { slug: "sesame-oil", name: "Sesame oil", category: "fat", kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fibreG: null, unitGrams: 5, unitLabel: "tsp", aliases: ["toasted sesame oil"] },
  { slug: "coconut-oil", name: "Coconut oil", category: "fat", kcal: 862, proteinG: 0, carbsG: 0, fatG: 100, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: [] },
  { slug: "butter", name: "Butter", category: "fat", kcal: 717, proteinG: 0.9, carbsG: 0.1, fatG: 81, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: ["salted butter", "unsalted butter"] },
  { slug: "ghee", name: "Ghee", category: "fat", kcal: 900, proteinG: 0, carbsG: 0, fatG: 99.8, fibreG: null, unitGrams: 14, unitLabel: "tbsp", aliases: ["clarified butter"] },
  { slug: "margarine", name: "Margarine spread", category: "fat", kcal: 540, proteinG: 0.2, carbsG: 0.6, fatG: 60, fibreG: null, unitGrams: 10, unitLabel: "spread on a slice", aliases: ["sunflower spread", "olive spread"] },
  { slug: "low-fat-spread", name: "Low-fat spread", category: "fat", kcal: 355, proteinG: 0.4, carbsG: 1, fatG: 39, fibreG: null, unitGrams: 10, unitLabel: "spread on a slice", aliases: ["light spread", "reduced fat spread"] },
  { slug: "mayonnaise", name: "Mayonnaise", category: "fat", kcal: 680, proteinG: 1, carbsG: 1.5, fatG: 75, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["mayo", "full fat mayonnaise"] },
  { slug: "mayonnaise-light", name: "Mayonnaise, light", category: "fat", kcal: 297, proteinG: 1, carbsG: 8, fatG: 28, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["light mayo", "reduced fat mayonnaise"] },
  { slug: "coconut-milk-tinned", name: "Coconut milk, tinned", category: "fat", kcal: 197, proteinG: 2, carbsG: 3, fatG: 20, fibreG: null, unitGrams: 400, unitLabel: "tin", aliases: ["coconut milk", "full fat coconut milk"] },
  { slug: "coconut-milk-light", name: "Coconut milk, light", category: "fat", kcal: 73, proteinG: 0.7, carbsG: 1.6, fatG: 7, fibreG: null, unitGrams: 400, unitLabel: "tin", aliases: ["reduced fat coconut milk", "light coconut milk"] },
  { slug: "chocolate-spread", name: "Chocolate hazelnut spread", category: "fat", kcal: 539, proteinG: 6, carbsG: 57, fatG: 31, fibreG: 3, unitGrams: 15, unitLabel: "tbsp", aliases: ["nutella", "chocolate spread"] },

  // ── Sauces, condiments, stock and baking ──────────────────────────────────
  { slug: "ketchup", name: "Tomato ketchup", category: "sauce", kcal: 102, proteinG: 1.2, carbsG: 24, fatG: 0.1, fibreG: null, unitGrams: 17, unitLabel: "tbsp", aliases: ["tomato sauce", "catsup"] },
  { slug: "mustard", name: "Mustard", category: "sauce", kcal: 66, proteinG: 4, carbsG: 5, fatG: 3.5, fibreG: null, unitGrams: 5, unitLabel: "tsp", aliases: ["dijon mustard", "wholegrain mustard", "english mustard"] },
  { slug: "soy-sauce", name: "Soy sauce", category: "sauce", kcal: 53, proteinG: 8, carbsG: 5, fatG: 0.1, fibreG: null, unitGrams: 16, unitLabel: "tbsp", aliases: ["light soy sauce", "tamari", "shoyu"] },
  { slug: "sriracha", name: "Sriracha", category: "sauce", kcal: 93, proteinG: 1.9, carbsG: 19, fatG: 0.9, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["hot sauce", "chilli sauce"] },
  { slug: "sweet-chilli-sauce", name: "Sweet chilli sauce", category: "sauce", kcal: 225, proteinG: 0.3, carbsG: 55, fatG: 0.1, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["thai sweet chilli"] },
  { slug: "bbq-sauce", name: "Barbecue sauce", category: "sauce", kcal: 172, proteinG: 0.8, carbsG: 41, fatG: 0.6, fibreG: null, unitGrams: 17, unitLabel: "tbsp", aliases: ["bbq sauce", "barbeque sauce"] },
  { slug: "mango-chutney", name: "Mango chutney", category: "sauce", kcal: 250, proteinG: 0.4, carbsG: 60, fatG: 0.5, fibreG: null, unitGrams: 20, unitLabel: "tbsp", aliases: ["chutney"] },
  { slug: "pesto", name: "Pesto", category: "sauce", kcal: 460, proteinG: 5, carbsG: 4, fatG: 47, fibreG: 2, unitGrams: 15, unitLabel: "tbsp", aliases: ["green pesto", "basil pesto"] },
  { slug: "tzatziki", name: "Tzatziki", category: "sauce", kcal: 130, proteinG: 3.5, carbsG: 3, fatG: 11, fibreG: null, unitGrams: 50, unitLabel: "portion", aliases: ["cucumber yoghurt dip", "raita"] },
  { slug: "salsa", name: "Salsa", category: "sauce", kcal: 36, proteinG: 1.5, carbsG: 7, fatG: 0.2, fibreG: 1.5, unitGrams: 30, unitLabel: "tbsp", aliases: ["tomato salsa", "pico de gallo"] },
  { slug: "guacamole", name: "Guacamole", category: "sauce", kcal: 150, proteinG: 2, carbsG: 3, fatG: 14, fibreG: 5, unitGrams: 50, unitLabel: "portion", aliases: ["avocado dip"] },
  { slug: "pasta-sauce-tomato", name: "Tomato pasta sauce, jarred", category: "sauce", kcal: 55, proteinG: 1.7, carbsG: 7, fatG: 2, fibreG: 1.5, unitGrams: 250, unitLabel: "half jar", aliases: ["tomato sauce", "arrabbiata sauce", "bolognese sauce", "pasta sauce"] },
  { slug: "curry-sauce-tikka", name: "Tikka masala sauce, jarred", category: "sauce", kcal: 110, proteinG: 2, carbsG: 9, fatG: 7, fibreG: 1.5, unitGrams: 250, unitLabel: "half jar", aliases: ["curry sauce", "tikka sauce", "balti sauce"] },
  { slug: "curry-sauce-korma", name: "Korma sauce, jarred", category: "sauce", kcal: 155, proteinG: 2.5, carbsG: 11, fatG: 11, fibreG: 1.5, unitGrams: 250, unitLabel: "half jar", aliases: ["korma"] },
  { slug: "green-curry-paste", name: "Thai green curry paste", category: "sauce", kcal: 130, proteinG: 3, carbsG: 14, fatG: 6, fibreG: 3, unitGrams: 15, unitLabel: "tbsp", aliases: ["green curry paste", "thai curry paste", "red curry paste"] },
  { slug: "harissa", name: "Harissa paste", category: "sauce", kcal: 120, proteinG: 3, carbsG: 9, fatG: 8, fibreG: 3, unitGrams: 15, unitLabel: "tbsp", aliases: ["rose harissa"] },
  { slug: "caesar-dressing", name: "Caesar dressing", category: "sauce", kcal: 460, proteinG: 2, carbsG: 4, fatG: 48, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["salad dressing"] },
  { slug: "caesar-dressing-light", name: "Caesar dressing, light", category: "sauce", kcal: 160, proteinG: 2, carbsG: 7, fatG: 13, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["light caesar dressing", "light salad dressing"] },
  { slug: "vinaigrette", name: "Vinaigrette dressing", category: "sauce", kcal: 300, proteinG: 0.5, carbsG: 8, fatG: 30, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["french dressing", "mustard dressing", "oil and vinegar dressing"] },
  { slug: "gravy", name: "Gravy, made up", category: "sauce", kcal: 35, proteinG: 0.6, carbsG: 5, fatG: 1.3, fibreG: null, unitGrams: 70, unitLabel: "ladle", aliases: ["gravy granules made up"] },
  { slug: "stock", name: "Stock, made up", category: "sauce", kcal: 6, proteinG: 0.6, carbsG: 0.7, fatG: 0.1, fibreG: null, unitGrams: 250, unitLabel: "mug", aliases: ["chicken stock", "vegetable stock", "beef stock", "bouillon", "broth"] },
  { slug: "honey", name: "Honey", category: "sauce", kcal: 304, proteinG: 0.3, carbsG: 82, fatG: 0, fibreG: null, unitGrams: 7, unitLabel: "tsp", aliases: ["runny honey", "clear honey"] },
  { slug: "maple-syrup", name: "Maple syrup", category: "sauce", kcal: 260, proteinG: 0, carbsG: 67, fatG: 0.1, fibreG: null, unitGrams: 20, unitLabel: "tbsp", aliases: ["syrup"] },
  { slug: "jam", name: "Jam", category: "sauce", kcal: 260, proteinG: 0.4, carbsG: 65, fatG: 0.1, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["strawberry jam", "preserve", "jelly"] },
  { slug: "marmite", name: "Yeast extract spread", category: "sauce", kcal: 231, proteinG: 34, carbsG: 24, fatG: 0.5, fibreG: 3, unitGrams: 4, unitLabel: "tsp", aliases: ["marmite", "vegemite", "yeast extract"] },
  { slug: "sugar-white", name: "Sugar, white", category: "sauce", kcal: 400, proteinG: 0, carbsG: 100, fatG: 0, fibreG: null, unitGrams: 4, unitLabel: "tsp", aliases: ["granulated sugar", "caster sugar"] },
  { slug: "sugar-brown", name: "Sugar, brown", category: "sauce", kcal: 380, proteinG: 0, carbsG: 98, fatG: 0, fibreG: null, unitGrams: 4, unitLabel: "tsp", aliases: ["demerara sugar", "muscovado"] },

  // ── Drinks ────────────────────────────────────────────────────────────────
  { slug: "orange-juice", name: "Orange juice", category: "drink", kcal: 45, proteinG: 0.7, carbsG: 10.4, fatG: 0.2, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: ["oj", "fresh orange juice"] },
  { slug: "apple-juice", name: "Apple juice", category: "drink", kcal: 46, proteinG: 0.1, carbsG: 11, fatG: 0.1, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: [] },
  { slug: "cranberry-juice", name: "Cranberry juice", category: "drink", kcal: 46, proteinG: 0.1, carbsG: 11.5, fatG: 0.1, fibreG: null, unitGrams: 250, unitLabel: "glass (250ml)", aliases: [] },
  { slug: "fruit-smoothie", name: "Fruit smoothie", category: "drink", kcal: 55, proteinG: 0.7, carbsG: 13, fatG: 0.2, fibreG: 1, unitGrams: 250, unitLabel: "bottle (250ml)", aliases: ["smoothie"] },
  { slug: "cola", name: "Cola", category: "drink", kcal: 42, proteinG: 0, carbsG: 10.6, fatG: 0, fibreG: null, unitGrams: 330, unitLabel: "can (330ml)", aliases: ["coke", "pepsi", "fizzy drink", "soda"] },
  { slug: "cola-diet", name: "Diet cola", category: "drink", kcal: 1, proteinG: 0, carbsG: 0, fatG: 0, fibreG: null, unitGrams: 330, unitLabel: "can (330ml)", aliases: ["diet coke", "coke zero", "sugar free cola"] },
  { slug: "lemonade", name: "Lemonade", category: "drink", kcal: 38, proteinG: 0, carbsG: 9.5, fatG: 0, fibreG: null, unitGrams: 330, unitLabel: "can (330ml)", aliases: ["sprite", "7up"] },
  { slug: "tonic-water", name: "Tonic water", category: "drink", kcal: 34, proteinG: 0, carbsG: 8.6, fatG: 0, fibreG: null, unitGrams: 150, unitLabel: "mixer", aliases: ["indian tonic water"] },
  { slug: "energy-drink", name: "Energy drink", category: "drink", kcal: 45, proteinG: 0.4, carbsG: 11, fatG: 0, fibreG: null, unitGrams: 250, unitLabel: "can (250ml)", aliases: ["red bull", "monster"] },
  { slug: "sports-drink", name: "Sports drink", category: "drink", kcal: 25, proteinG: 0, carbsG: 6, fatG: 0, fibreG: null, unitGrams: 500, unitLabel: "bottle (500ml)", aliases: ["isotonic drink", "gatorade", "lucozade sport"] },
  { slug: "coffee-black", name: "Black coffee", category: "drink", kcal: 2, proteinG: 0.1, carbsG: 0, fatG: 0, fibreG: null, unitGrams: 250, unitLabel: "mug", aliases: ["americano", "filter coffee", "espresso"] },
  { slug: "latte", name: "Latte, semi-skimmed", category: "drink", kcal: 47, proteinG: 3.2, carbsG: 4.4, fatG: 1.6, fibreG: null, unitGrams: 340, unitLabel: "medium latte", aliases: ["cappuccino", "flat white", "milky coffee"] },
  { slug: "lager", name: "Lager", category: "drink", kcal: 43, proteinG: 0.5, carbsG: 3.5, fatG: 0, fibreG: null, unitGrams: 568, unitLabel: "pint", aliases: ["beer", "pilsner", "premium lager"] },
  { slug: "ale", name: "Ale or bitter", category: "drink", kcal: 35, proteinG: 0.4, carbsG: 3, fatG: 0, fibreG: null, unitGrams: 568, unitLabel: "pint", aliases: ["bitter", "real ale", "pale ale"] },
  { slug: "stout", name: "Stout", category: "drink", kcal: 35, proteinG: 0.4, carbsG: 3, fatG: 0, fibreG: null, unitGrams: 568, unitLabel: "pint", aliases: ["guinness", "porter"] },
  { slug: "cider", name: "Cider, dry", category: "drink", kcal: 44, proteinG: 0, carbsG: 3, fatG: 0, fibreG: null, unitGrams: 568, unitLabel: "pint", aliases: ["apple cider"] },
  { slug: "wine-red", name: "Red wine", category: "drink", kcal: 85, proteinG: 0.1, carbsG: 2.6, fatG: 0, fibreG: null, unitGrams: 175, unitLabel: "large glass (175ml)", aliases: ["wine", "merlot", "cabernet"] },
  { slug: "wine-white", name: "White wine, dry", category: "drink", kcal: 82, proteinG: 0.1, carbsG: 2.6, fatG: 0, fibreG: null, unitGrams: 175, unitLabel: "large glass (175ml)", aliases: ["sauvignon blanc", "pinot grigio", "chardonnay"] },
  { slug: "prosecco", name: "Prosecco", category: "drink", kcal: 72, proteinG: 0.1, carbsG: 2, fatG: 0, fibreG: null, unitGrams: 125, unitLabel: "glass (125ml)", aliases: ["champagne", "sparkling wine", "cava"] },
  { slug: "spirits-40", name: "Spirits, 40%", category: "drink", kcal: 231, proteinG: 0, carbsG: 0, fatG: 0, fibreG: null, unitGrams: 25, unitLabel: "single (25ml)", aliases: ["vodka", "gin", "whisky", "rum", "tequila", "bourbon"] },

  // ── Snacks, sweets and convenience ────────────────────────────────────────
  { slug: "protein-powder-whey", name: "Whey protein powder", category: "snack", kcal: 380, proteinG: 75, carbsG: 8, fatG: 6, fibreG: 1, unitGrams: 30, unitLabel: "scoop", aliases: ["protein powder", "whey", "vanilla protein powder", "protein shake powder"] },
  { slug: "protein-bar", name: "Protein bar", category: "snack", kcal: 380, proteinG: 32, carbsG: 32, fatG: 13, fibreG: 8, unitGrams: 60, unitLabel: "bar", aliases: ["protein bars"] },
  { slug: "cereal-bar", name: "Cereal bar", category: "snack", kcal: 400, proteinG: 5, carbsG: 65, fatG: 13, fibreG: 4, unitGrams: 35, unitLabel: "bar", aliases: ["granola bar", "breakfast bar"] },
  { slug: "dark-chocolate", name: "Dark chocolate, 70%", category: "snack", kcal: 570, proteinG: 8, carbsG: 34, fatG: 42, fibreG: 10, unitGrams: 10, unitLabel: "square", aliases: ["dark chocolate", "plain chocolate"] },
  { slug: "milk-chocolate", name: "Milk chocolate", category: "snack", kcal: 535, proteinG: 7.5, carbsG: 57, fatG: 30, fibreG: 2.5, unitGrams: 10, unitLabel: "square", aliases: ["chocolate", "chocolate bar"] },
  { slug: "crisps", name: "Crisps, ready salted", category: "snack", kcal: 536, proteinG: 6.6, carbsG: 53, fatG: 35, fibreG: 4, unitGrams: 25, unitLabel: "small bag", aliases: ["potato chips", "chips", "salted crisps"] },
  { slug: "tortilla-chips", name: "Tortilla chips", category: "snack", kcal: 500, proteinG: 7, carbsG: 60, fatG: 25, fibreG: 5, unitGrams: 30, unitLabel: "portion", aliases: ["doritos", "nachos", "corn chips"] },
  { slug: "popcorn", name: "Popcorn, plain", category: "snack", kcal: 387, proteinG: 13, carbsG: 66, fatG: 4.5, fibreG: 14.5, unitGrams: 25, unitLabel: "bag", aliases: ["air popped popcorn"] },
  { slug: "pretzels", name: "Pretzels", category: "snack", kcal: 380, proteinG: 10, carbsG: 80, fatG: 3, fibreG: 3, unitGrams: 30, unitLabel: "portion", aliases: [] },
  { slug: "rice-cakes", name: "Rice cakes", category: "snack", kcal: 387, proteinG: 8, carbsG: 81, fatG: 3, fibreG: 3, unitGrams: 9, unitLabel: "rice cake", aliases: ["puffed rice cake"] },
  { slug: "digestive-biscuit", name: "Digestive biscuit", category: "snack", kcal: 480, proteinG: 6.5, carbsG: 63, fatG: 22, fibreG: 3, unitGrams: 15, unitLabel: "biscuit", aliases: ["digestives", "sweet biscuit"] },
  { slug: "chocolate-digestive", name: "Chocolate digestive", category: "snack", kcal: 495, proteinG: 6, carbsG: 63, fatG: 24, fibreG: 3, unitGrams: 17, unitLabel: "biscuit", aliases: ["chocolate biscuit"] },
  { slug: "cookie-chocolate-chip", name: "Chocolate chip cookie", category: "snack", kcal: 480, proteinG: 5, carbsG: 64, fatG: 23, fibreG: 2.5, unitGrams: 30, unitLabel: "cookie", aliases: ["cookies"] },
  { slug: "blueberry-muffin", name: "Blueberry muffin", category: "snack", kcal: 380, proteinG: 5, carbsG: 50, fatG: 18, fibreG: 2, unitGrams: 100, unitLabel: "muffin", aliases: ["muffin"] },
  { slug: "doughnut", name: "Doughnut", category: "snack", kcal: 420, proteinG: 6, carbsG: 50, fatG: 22, fibreG: 2, unitGrams: 60, unitLabel: "doughnut", aliases: ["donut", "jam doughnut"] },

  // ── Prepared and convenience meals ────────────────────────────────────────
  { slug: "oven-chips", name: "Oven chips, baked", category: "prepared", kcal: 190, proteinG: 3, carbsG: 29, fatG: 6.5, fibreG: 3, unitGrams: 150, unitLabel: "portion", aliases: ["chips", "french fries", "fries", "frozen chips"] },
  { slug: "roast-potatoes", name: "Roast potatoes", category: "prepared", kcal: 165, proteinG: 3, carbsG: 26, fatG: 5, fibreG: 2.5, unitGrams: 150, unitLabel: "portion", aliases: ["roasties"] },
  { slug: "mashed-potato", name: "Mashed potato, with butter and milk", category: "prepared", kcal: 105, proteinG: 2, carbsG: 15, fatG: 4, fibreG: 1.5, unitGrams: 180, unitLabel: "portion", aliases: ["mash", "creamed potato"] },
  { slug: "fish-fingers", name: "Fish fingers, baked", category: "prepared", kcal: 220, proteinG: 13, carbsG: 19, fatG: 10, fibreG: 1.5, unitGrams: 28, unitLabel: "fish finger", aliases: ["fish sticks"] },
  { slug: "chicken-nuggets", name: "Chicken nuggets, baked", category: "prepared", kcal: 290, proteinG: 15, carbsG: 17, fatG: 18, fibreG: 1.5, unitGrams: 18, unitLabel: "nugget", aliases: ["chicken dippers"] },
  { slug: "pizza-margherita", name: "Pizza, margherita, cooked", category: "prepared", kcal: 265, proteinG: 11, carbsG: 33, fatG: 9, fibreG: 2.5, unitGrams: 125, unitLabel: "slice", aliases: ["pizza", "cheese pizza"] },
  { slug: "vegetable-soup", name: "Vegetable soup, tinned", category: "prepared", kcal: 45, proteinG: 1.5, carbsG: 7, fatG: 1, fibreG: 1.5, unitGrams: 400, unitLabel: "tin", aliases: ["soup", "tomato soup"] },
  { slug: "coleslaw-dressed", name: "Coleslaw, with mayonnaise", category: "prepared", kcal: 190, proteinG: 1, carbsG: 7, fatG: 17, fibreG: 2, unitGrams: 80, unitLabel: "portion", aliases: ["coleslaw", "slaw"] },
  { slug: "sausage-roll", name: "Sausage roll", category: "prepared", kcal: 340, proteinG: 8, carbsG: 27, fatG: 22, fibreG: 1.5, unitGrams: 60, unitLabel: "sausage roll", aliases: [] },
  { slug: "hash-browns", name: "Hash browns, baked", category: "prepared", kcal: 265, proteinG: 3, carbsG: 35, fatG: 12, fibreG: 2.5, unitGrams: 45, unitLabel: "hash brown", aliases: [] },
  { slug: "garlic-bread", name: "Garlic bread", category: "prepared", kcal: 350, proteinG: 7, carbsG: 40, fatG: 17, fibreG: 2.5, unitGrams: 40, unitLabel: "slice", aliases: ["garlic baguette"] },
  { slug: "chicken-goujons", name: "Breaded chicken goujons, baked", category: "prepared", kcal: 240, proteinG: 20, carbsG: 15, fatG: 11, fibreG: 1, unitGrams: 25, unitLabel: "goujon", aliases: ["breaded chicken", "chicken strips", "southern fried chicken strips"] },
  { slug: "lasagne-ready-meal", name: "Beef lasagne, ready meal", category: "prepared", kcal: 130, proteinG: 7, carbsG: 12, fatG: 6, fibreG: 1, unitGrams: 400, unitLabel: "ready meal", aliases: ["lasagne", "lasagna"] },
  { slug: "tikka-masala-ready-meal", name: "Chicken tikka masala, ready meal", category: "prepared", kcal: 145, proteinG: 9, carbsG: 8, fatG: 8, fibreG: 1, unitGrams: 375, unitLabel: "ready meal", aliases: ["chicken curry", "tikka masala"] },

  // ── A second pass over the everyday shelf ─────────────────────────────────
  { slug: "chicken-slices-deli", name: "Chicken slices, deli", category: "meat", kcal: 110, proteinG: 21, carbsG: 1, fatG: 2, fibreG: null, unitGrams: 20, unitLabel: "slice", aliases: ["sliced chicken", "wafer thin chicken"] },
  { slug: "turkey-slices-deli", name: "Turkey slices, deli", category: "meat", kcal: 105, proteinG: 17, carbsG: 1.5, fatG: 3, fibreG: null, unitGrams: 20, unitLabel: "slice", aliases: ["sliced turkey", "wafer thin turkey"] },
  { slug: "beef-burger-cooked", name: "Beef burger, cooked", category: "meat", kcal: 250, proteinG: 25, carbsG: 1, fatG: 16, fibreG: null, unitGrams: 110, unitLabel: "burger", aliases: ["hamburger patty", "beef patty"] },
  { slug: "crab-sticks", name: "Crab sticks", category: "fish", kcal: 95, proteinG: 8, carbsG: 14, fatG: 0.5, fibreG: null, unitGrams: 17, unitLabel: "stick", aliases: ["surimi", "seafood sticks"] },
  { slug: "edam", name: "Edam", category: "dairy", kcal: 330, proteinG: 26, carbsG: 1.5, fatG: 25, fibreG: null, unitGrams: 30, unitLabel: "portion", aliases: ["gouda", "babybel"] },
  { slug: "cheese-slice-processed", name: "Processed cheese slice", category: "dairy", kcal: 290, proteinG: 16, carbsG: 7, fatG: 22, fibreG: null, unitGrams: 20, unitLabel: "slice", aliases: ["burger cheese", "american cheese", "cheese singles"] },
  { slug: "custard", name: "Custard, ready to serve", category: "dairy", kcal: 100, proteinG: 3, carbsG: 16, fatG: 3, fibreG: null, unitGrams: 120, unitLabel: "portion", aliases: [] },
  { slug: "rice-pudding", name: "Rice pudding, tinned", category: "dairy", kcal: 90, proteinG: 3.3, carbsG: 16, fatG: 1.6, fibreG: null, unitGrams: 200, unitLabel: "half tin", aliases: [] },
  { slug: "porridge-milk", name: "Porridge, made with semi-skimmed milk", category: "grain", kcal: 90, proteinG: 4, carbsG: 12, fatG: 2.5, fibreG: 1.5, unitGrams: 250, unitLabel: "bowl", aliases: ["oatmeal with milk"] },
  { slug: "pitta-white", name: "White pitta bread", category: "grain", kcal: 275, proteinG: 9, carbsG: 55, fatG: 1.2, fibreG: 2.5, unitGrams: 60, unitLabel: "pitta", aliases: ["pita"] },
  { slug: "pancake", name: "Pancake", category: "grain", kcal: 227, proteinG: 6.4, carbsG: 28, fatG: 9.7, fibreG: 1, unitGrams: 40, unitLabel: "pancake", aliases: ["american pancake", "scotch pancake"] },
  { slug: "scone", name: "Scone, plain", category: "grain", kcal: 362, proteinG: 7.2, carbsG: 54, fatG: 14.6, fibreG: 2, unitGrams: 60, unitLabel: "scone", aliases: ["fruit scone"] },
  { slug: "cream-cracker", name: "Cream cracker", category: "grain", kcal: 440, proteinG: 9.5, carbsG: 68, fatG: 16, fibreG: 3, unitGrams: 7, unitLabel: "cracker", aliases: ["water biscuit", "savoury cracker", "crackers"] },
  { slug: "chickpeas-dry", name: "Chickpeas, dry", category: "legume", kcal: 364, proteinG: 19, carbsG: 50, fatG: 6, fibreG: 17, unitGrams: 100, unitLabel: "portion", aliases: ["dried chickpeas"] },
  { slug: "mixed-bean-salad", name: "Mixed bean salad, tinned", category: "legume", kcal: 95, proteinG: 6, carbsG: 14, fatG: 0.7, fibreG: 4.5, unitGrams: 200, unitLabel: "half tin", aliases: ["five bean salad", "mixed beans"] },
  { slug: "pak-choi", name: "Pak choi", category: "vegetable", kcal: 13, proteinG: 1.5, carbsG: 1, fatG: 0.2, fibreG: 1, unitGrams: 100, unitLabel: "head", aliases: ["bok choy", "chinese cabbage"] },
  { slug: "parsnip", name: "Parsnip", category: "vegetable", kcal: 64, proteinG: 1.8, carbsG: 12.5, fatG: 1.1, fibreG: 4.6, unitGrams: 130, unitLabel: "parsnip", aliases: ["parsnips"] },
  { slug: "apricot", name: "Apricot", category: "fruit", kcal: 48, proteinG: 1.4, carbsG: 9, fatG: 0.4, fibreG: 2, unitGrams: 35, unitLabel: "apricot", aliases: ["fresh apricots"] },
  { slug: "papaya", name: "Papaya", category: "fruit", kcal: 43, proteinG: 0.5, carbsG: 10, fatG: 0.3, fibreG: 1.7, unitGrams: 150, unitLabel: "portion", aliases: ["pawpaw"] },
  { slug: "pomegranate-seeds", name: "Pomegranate seeds", category: "fruit", kcal: 83, proteinG: 1.7, carbsG: 16, fatG: 1.2, fibreG: 4, unitGrams: 80, unitLabel: "portion", aliases: ["pomegranate"] },
  { slug: "prunes", name: "Prunes", category: "fruit", kcal: 240, proteinG: 2.2, carbsG: 57, fatG: 0.4, fibreG: 7, unitGrams: 10, unitLabel: "prune", aliases: ["dried plums"] },
  { slug: "dried-cranberries", name: "Dried cranberries", category: "fruit", kcal: 308, proteinG: 0.1, carbsG: 77, fatG: 1.4, fibreG: 5.7, unitGrams: 20, unitLabel: "handful", aliases: ["craisins"] },
  { slug: "hemp-seeds", name: "Hemp seeds", category: "nut", kcal: 553, proteinG: 32, carbsG: 8.7, fatG: 49, fibreG: 4, unitGrams: 10, unitLabel: "tbsp", aliases: ["hemp hearts"] },
  { slug: "hoisin-sauce", name: "Hoisin sauce", category: "sauce", kcal: 220, proteinG: 3, carbsG: 48, fatG: 3.4, fibreG: 2, unitGrams: 16, unitLabel: "tbsp", aliases: ["chinese barbecue sauce"] },
  { slug: "fish-sauce", name: "Fish sauce", category: "sauce", kcal: 35, proteinG: 5, carbsG: 3.6, fatG: 0, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["nam pla"] },
  { slug: "ranch-dressing", name: "Ranch dressing", category: "sauce", kcal: 430, proteinG: 1, carbsG: 6, fatG: 45, fibreG: null, unitGrams: 15, unitLabel: "tbsp", aliases: ["blue cheese dressing"] },
  { slug: "hot-chocolate", name: "Hot chocolate, made with milk", category: "drink", kcal: 80, proteinG: 3.4, carbsG: 11, fatG: 2.5, fibreG: null, unitGrams: 250, unitLabel: "mug", aliases: ["cocoa", "drinking chocolate"] },
  { slug: "tea-with-milk", name: "Tea with milk", category: "drink", kcal: 6, proteinG: 0.4, carbsG: 0.5, fatG: 0.2, fibreG: null, unitGrams: 250, unitLabel: "mug", aliases: ["builders tea", "cup of tea"] },
  { slug: "coconut-water", name: "Coconut water", category: "drink", kcal: 19, proteinG: 0.7, carbsG: 3.7, fatG: 0.2, fibreG: null, unitGrams: 330, unitLabel: "carton", aliases: [] },
  { slug: "protein-shake-rtd", name: "Protein shake, ready to drink", category: "drink", kcal: 60, proteinG: 10, carbsG: 3, fatG: 0.8, fibreG: null, unitGrams: 330, unitLabel: "bottle", aliases: ["protein drink", "protein milkshake"] },
  { slug: "protein-powder-plant", name: "Plant protein powder", category: "snack", kcal: 400, proteinG: 80, carbsG: 4, fatG: 6.5, fibreG: 3, unitGrams: 30, unitLabel: "scoop", aliases: ["pea protein", "vegan protein powder", "soya protein powder"] },
  { slug: "shortbread", name: "Shortbread", category: "snack", kcal: 498, proteinG: 5.9, carbsG: 64, fatG: 26, fibreG: 2, unitGrams: 20, unitLabel: "finger", aliases: [] },
  { slug: "jelly-sweets", name: "Jelly sweets", category: "snack", kcal: 343, proteinG: 6.9, carbsG: 77, fatG: 0.2, fibreG: null, unitGrams: 25, unitLabel: "handful", aliases: ["haribo", "gummy sweets", "gummy bears", "wine gums"] },
];
