#!/usr/bin/env bash
# Regenerate .env.test from .env: the same keys, the database swapped for the
# local Postgres the suites run against. Run after changing .env.
set -euo pipefail
cd "$(dirname "$0")/.."
LOCAL="postgres://$(whoami)@localhost:5432/plate_test"
{
  echo "# The test suites' environment: production's, with the database swapped for a"
  echo "# local Postgres. Regenerated by \`npm run env:test\`; ignored by git."
  sed -E "s#^DATABASE_URL=.*#DATABASE_URL=${LOCAL}#; s#^DATABASE_URL_DIRECT=.*#DATABASE_URL_DIRECT=${LOCAL}#" .env
} > .env.test
echo "wrote .env.test → ${LOCAL}"
